## AI Text Detection ##

We run Pangram on all cleaned sampled texted across all sampled candidates. The final dataframe returns the given CSV with the additional columns of label_final, ai_assistance_final, confidence_final, fraction_ai, fraction_ai_assisted, fraction_human, and num_ai_segments; all of these scores are obtained with the Pangram API using research credits

In [1]:
import pandas as pd
from pangram import Pangram
import numpy as np
import random
import re
from collections import Counter #for extracting labels and confidence majorities with pangram
import os
from dotenv import load_dotenv

In [2]:
governor_data = pd.read_csv("../governor_content.csv")

In [3]:
ag_data = pd.read_csv("../ag_content.csv")

In [7]:
mayor_data = pd.read_csv("../mayor_content.csv")

In [9]:
us_senate_data = pd.read_csv("../us_senate_content.csv")

In [172]:
us_house_data = pd.read_csv("../us_house_content.csv")

In [174]:
state_house_data = pd.read_csv("../state_house_content.csv")

In [175]:
state_senate_data = pd.read_csv("../state_senate_content.csv")

In [57]:
load_dotenv()
pangram_client = Pangram(api_key=os.getenv("PANGRAM_API_KEY"))

### Data Cleaning ###
This notebook uses data queried from camplinks.db from the Content table to get the sampled text for all candidates in our database.This is loaded in as "data". We then clean the dataframe by dropping rows where the unprocessed_text and sampled_text are both NA or where sampled_text = ERROR: could not fetch page. 

The dataframe also contains features of candidates that have been combined from the camplinks.db, allowing for easier future analysis using only one CSV

In [11]:
#add columns to datasets to fill in with pangram results

def add_columns(df):
    columns_to_add = [
        'AI_label',
        'assistance_score',
        'confidence',
        'fraction_ai',
        'fraction_ai_assisted',
        'fraction_human',
        'num_ai_segments'
    ]
    
    for col in columns_to_add:
        df[col] = float('nan')

    return df


def clean_data(df):
    df_filtered = df[~(df['unprocessed_text'].isna() & df['sampled_text'].isna())]
    df_cleaned = df_filtered[df_filtered['sampled_text'] != 'ERROR: could not fetch page']
    return df_cleaned

In [13]:
#some exploratory functions:

def avg_word_count(df):
    return df['sampled_text'].str.split().str.len().mean()

def cand_amount(df):
    return df['candidate_name'].nunique()

Clean and add columns:

In [15]:
gov_cleaned = clean_data(governor_data)
gov_added = add_columns(gov_cleaned)

In [17]:
ag_cleaned = clean_data(ag_data)
ag_added = add_columns(ag_cleaned)

In [19]:
mayor_cleaned = clean_data(mayor_data)
mayor_added = add_columns(mayor_cleaned)

In [21]:
us_senate_cleaned = clean_data(us_senate_data)
us_senate_added = add_columns(us_senate_cleaned)

In [192]:
us_house_cleaned = clean_data(us_house_data)
us_house_added = add_columns(us_house_cleaned)

In [194]:
state_senate_cleaned = clean_data(state_senate_data)
state_senate_added = add_columns(state_senate_cleaned)

In [196]:
state_house_cleaned = clean_data(state_house_data)
state_house_added = add_columns(state_house_cleaned)

Get some exploratory information

In [198]:
#exploratory info
print('governor candidates:', cand_amount(gov_added), '- average word count and text samples: ', avg_word_count(gov_added) , ', ' , len(gov_added))
print('attorney general candidates:', cand_amount(ag_added), '- average word count and text samples: ', avg_word_count(ag_added), ', ', len(ag_added))
print('mayoral candidates:', cand_amount(mayor_added), '- average word count and text samples: ', avg_word_count(mayor_added), ', ', len(mayor_added))
print('US senate candidates:', cand_amount(us_senate_added), '- average word count and text samples: ', avg_word_count(us_senate_added), ', ', len(us_senate_added))
print('US house candidates:', cand_amount(us_house_added), '- average word count and text samples: ', avg_word_count(us_house_added), ', ', len(us_house_added))
print('State senate candidates:', cand_amount(state_senate_added), '- average word count and text samples:  ', avg_word_count(state_senate_added), ', ', len(state_senate_added))
print('State house candidates:', cand_amount(state_house_added), ' - average word count and text samples: ', avg_word_count(state_house_added), ', ', len(state_house_added))

governor candidates: 29 - average word count and text samples:  242.83582089552237 ,  67
attorney general candidates: 26 - average word count and text samples:  206.02325581395348 ,  43
mayoral candidates: 155 - average word count and text samples:  281.3973941368078 ,  307
US senate candidates: 58 - average word count and text samples:  237.9624060150376 ,  133
US house candidates: 809 - average word count and text samples:  292.2930513595166 ,  1986
State senate candidates: 1469 - average word count and text samples:   242.05026769779892 ,  3362
State house candidates: 6615  - average word count and text samples:  238.12985064892715 ,  15333

In [200]:
#combine all tables together to view across all races (this is just exploratory, detection will be ran on individual dataframes(
combined = pd.concat([gov_added, ag_added, mayor_added, us_senate_added, us_house_added, state_senate_added, state_house_added], ignore_index=True)
combined.head()

,content_id,candidate_id,candidate_name,page_url,page_type,link_type,unprocessed_text,cleaned_text,sampled_text,race_type,year,AI_label,assistance_score,confidence,fraction_ai,fraction_ai_assisted,fraction_human,num_ai_segments
0,1,6179,Andy Beshear,https://andybeshear.com/,home,campaign_site,Andy Beshear Menu Meet Andy Meet Jacqueline An...,Andy Beshear Menu Meet Andy Meet Jacqueline An...,Andy Beshear Menu Meet Andy Meet Jacqueline An...,Governor,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,6180,Daniel Cameron,https://cameronforkentucky.com/,home,campaign_site,Menu News Facebook Twitter Instagram Donate › ...,Menu News Facebook Twitter Instagram Donate S...,I'm In! QUICK DONATE $25 $50 $100 ENTER AMOUNT...,Governor,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,6180,Daniel Cameron,https://cameronforkentucky.com/policies/terms,policy,campaign_site,Menu News Facebook Twitter Instagram Donate › ...,Menu News Facebook Twitter Instagram Donate S...,Data Privacy We will not share or sell your pe...,Governor,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,6180,Daniel Cameron,https://cameronforkentucky.com/policies/privacy,policy,campaign_site,Menu News Facebook Twitter Instagram Donate › ...,Menu News Facebook Twitter Instagram Donate S...,"This Privacy Policy explains how we collect, u...",Governor,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,6180,Daniel Cameron,https://cameronforkentucky.com/issues/,policy,campaign_site,Menu News Facebook Twitter Instagram Donate › ...,Menu News Facebook Twitter Instagram Donate S...,He will always oppose the radical green agenda...,Governor,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [147]:
print('Total candidates:', cand_amount(combined), ' - average word count and text samples: ', avg_word_count(combined), ', ', len(combined))

Total candidates: 9126  - average word count and text samples:  244.39164429372144 ,  21231

In [83]:
combined['page_type'].value_counts() / len(combined)

page_type
home      0.442560
about     0.293533
policy    0.263907
Name: count, dtype: float64

### Running AI Text Detection ###

In [ ]:
#add in empty columns so that we don't accidently lose any pangram data
#instead, automatically append an entire row once its done; additionally run in batches

In [23]:
#code source from pangram: https://pangram.readthedocs.io/en/latest/api/pangram.html

def check_AI(text):
    valid_API_call = False
    try:
        result = pangram_client.predict(text)
        valid_API_call = True
    except:
        fraction_ai = float('nan')
        fraction_ai_assisted = float('nan')
        fraction_human = float('nan')
        num_ai_segments = float('nan')
        AI_label = float('nan')
        confidence_final = float('nan')
        assistance_score = float('nan')

    if valid_API_call:
        AI_label = result['prediction_short']
        confidence_all = []
        ai_assistance_all = []
        fraction_ai = result['fraction_ai']
        fraction_ai_assisted = result['fraction_ai_assisted']
        fraction_human = result['fraction_human']
        num_ai_segments = result['num_ai_segments']

        #for some reason, confidence is only per-window. So to get it we need to average out window confidence. Though, there tends
        #to be only 1 or 2 windows so not big deal
        for window in result['windows']:
            confidence = window['confidence']
            confidence_all.append(confidence)

            ai_assistance_score = window['ai_assistance_score'] #same with these
            ai_assistance_all.append(ai_assistance_score)
            
        confidence = Counter(confidence_all).most_common(1)[0][0]
        assistance_score =  np.mean(ai_assistance_all)

    else:
        return ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']

    #print(AI_label, confidence, fraction_ai, fraction_ai_assisted, fraction_human, num_ai_segments)
    return [AI_label, assistance_score, confidence, fraction_ai, fraction_ai_assisted, fraction_human, num_ai_segments]

In [94]:
def check_entire_race(race_df):
    for idx, row in race_df.iterrows():
        try:
            result = check_AI(row['cleaned_text'])
            print(row['candidate_name'], result)
            race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result
        except Exception as e:
            print(f"Row {idx} failed: {e}")
            # row stays None/NaN, loop continues

In [153]:
#check_entire_race(us_senate_added)

Kari Lake ['Human', 0.058674976229667664, 'Medium', 0.0, 0.0, 1.0, 0]

/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_64413/2149402114.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Human' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result
/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_64413/2149402114.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Medium' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result

Kari Lake ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']

/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_64413/2149402114.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unable to run' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result
/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_64413/2149402114.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unable to run' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result
/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_64413/2149402114.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unable to run' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result
/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_64413/2149402114.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unable to run' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result
/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_64413/2149402114.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unable to run' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result

Kari Lake ['Human', 0.014941799454391003, 'High', 0.0, 0.0, 1.0, 0]
Ruben Gallego ['Human', 0.005045536223665944, 'High', 0.0, 0.0, 1.0, 0]
Ruben Gallego ['Human', 0.010151629336178303, 'High', 0.0, 0.0, 1.0, 0]
Ruben Gallego ['Human', 0.006716141011565924, 'High', 0.0, 0.0, 1.0, 0]
Ruben Gallego ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']
Ruben Gallego ['Human', 0.004454157315194607, 'High', 0.0, 0.0, 1.0, 0]
Ruben Gallego ['Human', 0.008216402493417263, 'High', 0.0, 0.0, 1.0, 0]
Ruben Gallego ['Human', 0.005655944813042879, 'High', 0.0, 0.0, 1.0, 0]
Ruben Gallego ['Human', 0.00491423299536109, 'High', 0.0, 0.0, 1.0, 0]
Adam B. Schiff ['Human', 0.007768214214593172, 'High', 0.0, 0.0, 1.0, 0]
Adam B. Schiff ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']
Adam B. Schiff ['Human', 0.0053487834923614105, 'High', 0.0, 0.0, 1.0, 0]
Steve Garvey ['Human', 0.0065215532667934895, 'High', 0.0, 0.0, 1.0, 0]
Christopher S. Murphy ['Human', 0.004320540931075811, 'High', 0.0, 0.0, 1.0, 0]
Christopher S. Murphy ['Human', 0.0051271050348683875, 'High', 0.0, 0.0, 1.0, 0]
Matthew M. Corey ['Human', 0.021321143954992294, 'High', 0.0, 0.0, 1.0, 0]
Lisa Blunt Rochester ['Human', 0.004278694728522429, 'High', 0.0, 0.0, 1.0, 0]
Lisa Blunt Rochester ['Human', 0.0071168504655361176, 'High', 0.0, 0.0, 1.0, 0]
Lisa Blunt Rochester ['Human', 0.006535376887768507, 'High', 0.0, 0.0, 1.0, 0]
Lisa Blunt Rochester ['Human', 0.01815187931060791, 'High', 0.0, 0.0, 1.0, 0]
Lisa Blunt Rochester ['Human', 0.006390857044607401, 'High', 0.0, 0.0, 1.0, 0]
Debbie Mucarsel-Powell ['Human', 0.005605597204218308, 'High', 0.0, 0.0, 1.0, 0]
Rick Scott ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']
Bob Mcdermott ['Human', 0.2648199200630188, 'Low', 0.0, 0.0, 1.0, 0]
Mazie K. Hirono ['Human', 0.005879802629351616, 'High', 0.0, 0.0, 1.0, 0]
Mazie K. Hirono ['Human', 0.005200216080993414, 'High', 0.0, 0.0, 1.0, 0]
Mazie K. Hirono ['Human', 0.004769904538989067, 'High', 0.0, 0.0, 1.0, 0]
Mazie K. Hirono ['Human', 0.005585611332207918, 'High', 0.0, 0.0, 1.0, 0]
Jim Banks ['Human', 0.003982893191277981, 'High', 0.0, 0.0, 1.0, 0]
Jim Banks ['Human', 0.004365506608400753, 'High', 0.0, 0.0, 1.0, 0]
Valerie Mccray ['Human', 0.004573614425227092, 'High', 0.0, 0.0, 1.0, 0]
Valerie Mccray ['Human', 0.004239722471562475, 'High', 0.0, 0.0, 1.0, 0]
Valerie Mccray ['Human', 0.06334768735211004, 'Medium', 0.0, 0.0, 1.0, 0]
Elizabeth Ann Warren ['Human', 0.0071240877732634544, 'High', 0.0, 0.0, 1.0, 0]
Elizabeth Ann Warren ['Human', 0.005157956387847662, 'High', 0.0, 0.0, 1.0, 0]
John Deaton ['Human', 0.004946868442108526, 'High', 0.0, 0.0, 1.0, 0]
John Deaton ['AI', 0.5924497842788696, 'Low', 1.0, 0.0, 0.0, 1]
Angela Alsobrooks ['Human', 0.007992289029061794, 'High', 0.0, 0.0, 1.0, 0]
Angela Alsobrooks ['Human', 0.012381128035485744, 'High', 0.0, 0.0, 1.0, 0]
Larry Hogan ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']
Angus S. King Jr. ['Human', 0.00846250168979168, 'High', 0.0, 0.0, 1.0, 0]
Angus S. King Jr. ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']
Demi Kouzounas ['Human', 0.0048009371384978294, 'High', 0.0, 0.0, 1.0, 0]
Demi Kouzounas ['Human', 0.021341567859053612, 'High', 0.0, 0.0, 1.0, 0]
Elissa Slotkin ['Human', 0.00480796629562974, 'High', 0.0, 0.0, 1.0, 0]
Elissa Slotkin ['Human', 0.005108480341732502, 'High', 0.0, 0.0, 1.0, 0]
Elissa Slotkin ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']
Elissa Slotkin ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']
Elissa Slotkin ['Human', 0.004747288767248392, 'High', 0.0, 0.0, 1.0, 0]
Elissa Slotkin ['Human', 0.005304357968270779, 'High', 0.0, 0.0, 1.0, 0]
Mike Rogers ['Human', 0.05164572224020958, 'Medium', 0.0, 0.0, 1.0, 0]
Amy Klobuchar ['Human', 0.0058662849478423595, 'High', 0.0, 0.0, 1.0, 0]
Royce White ['Human', 0.10075321048498154, 'Medium', 0.0, 0.0, 1.0, 0]
Josh Hawley ['Human', 0.006437868345528841, 'High', 0.0, 0.0, 1.0, 0]
Lucas Kunce ['Human', 0.004685312509536743, 'High', 0.0, 0.0, 1.0, 0]
Roger F. Wicker ['Human', 0.008066403679549694, 'High', 0.0, 0.0, 1.0, 0]
Ty Pinkins ['Human', 0.005822607781738043, 'High', 0.0, 0.0, 1.0, 0]
Ty Pinkins ['Human', 0.005038270261138678, 'High', 0.0, 0.0, 1.0, 0]
Jon Tester ['Human', 0.007878286764025688, 'High', 0.0, 0.0, 1.0, 0]
Jon Tester ['Human', 0.004958138699294067, 'High', 0.0, 0.0, 1.0, 0]
Jon Tester ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']
Tim Sheehy ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']
Kevin Cramer ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']
Kevin Cramer ['Human', 0.004020784981548786, 'High', 0.0, 0.0, 1.0, 0]
Kevin Cramer ['Mixed', 0.5632595240706557, 'Low', 0.0, 0.11753590325018896, 0.8824640967498111, 0]
Dan Osborn ['Human', 0.008001038804650307, 'High', 0.0, 0.0, 1.0, 0]
Dan Osborn ['Human', 0.004569520399125183, 'High', 0.0, 0.0, 1.0, 0]
Deb Fischer ['Human', 0.011212653402859965, 'High', 0.0, 0.0, 1.0, 0]
Andy Kim ['Human', 0.010192829184234142, 'High', 0.0, 0.0, 1.0, 0]
Andy Kim ['Human', 0.009194204583764076, 'High', 0.0, 0.0, 1.0, 0]
Andy Kim ['Human', 0.004826822783797979, 'High', 0.0, 0.0, 1.0, 0]
Martin Heinrich ['Human', 0.08699240535497665, 'Medium', 0.0, 0.0, 1.0, 0]
Martin Heinrich ['AI', 0.663730479138238, 'Low', 1.0, 0.0, 0.0, 1]
Martin Heinrich ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']
Jacky S. Rosen ['Human', 0.01021988969296217, 'High', 0.0, 0.0, 1.0, 0]
Jacky S. Rosen ['Human', 0.0046255080960690975, 'High', 0.0, 0.0, 1.0, 0]
Sam Brown ['Human', 0.030123770925337856, 'High', 0.0, 0.0, 1.0, 0]
Kirsten E. Gillibrand ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']
Kirsten E. Gillibrand ['Human', 0.0047079455107450485, 'High', 0.0, 0.0, 1.0, 0]
Bernie Moreno ['Human', 0.005371643230319023, 'High', 0.0, 0.0, 1.0, 0]
Bernie Moreno ['Human', 0.06812810152769089, 'Medium', 0.0, 0.0, 1.0, 0]
Sherrod Brown ['Human', 0.0047240303829312325, 'High', 0.0, 0.0, 1.0, 0]
Dave Mccormick ['Human', 0.004919086582958698, 'High', 0.0, 0.0, 1.0, 0]
Dave Mccormick ['Human', 0.005843314329536367, 'High', 0.0, 0.0, 1.0, 0]
Robert P Casey Jr ['Human', 0.004729846026748419, 'High', 0.0, 0.0, 1.0, 0]
Robert P Casey Jr ['Human', 0.004662956576794386, 'High', 0.0, 0.0, 1.0, 0]
Sheldon Whitehouse ['Human', 0.005985196214169264, 'High', 0.0, 0.0, 1.0, 0]
Sheldon Whitehouse ['Human', 0.006343228742480278, 'High', 0.0, 0.0, 1.0, 0]
Marsha Blackburn ['Human', 0.025388190503387403, 'High', 0.0, 0.0, 1.0, 0]
Marsha Blackburn ['Human', 0.03484184667468071, 'High', 0.0, 0.0, 1.0, 0]
Marsha Blackburn ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']
Marsha Blackburn ['Human', 0.004899672232568264, 'High', 0.0, 0.0, 1.0, 0]
Marsha Blackburn ['Human', 0.005929759703576565, 'High', 0.0, 0.0, 1.0, 0]
Marsha Blackburn ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']
Colin Allred ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']
Ted Cruz ['Human', 0.005136507097631693, 'High', 0.0, 0.0, 1.0, 0]
Caroline Gleich ['Human', 0.009829466231167316, 'High', 0.0, 0.0, 1.0, 0]
John Curtis ['Human', 0.08547747880220413, 'Medium', 0.0, 0.0, 1.0, 0]
John Curtis ['Human', 0.0055795954540371895, 'High', 0.0, 0.0, 1.0, 0]
Hung Cao ['Human', 0.006086681969463825, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.007659426890313625, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.0058019887655973434, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.005515699274837971, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.0045991456136107445, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.004545229021459818, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.004842336755245924, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.004679535515606403, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']
Timothy M. Kaine ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']
Timothy M. Kaine ['Human', 0.006804253906011581, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.006758694536983967, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.004854658152908087, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.0046029346995055676, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.006763790734112263, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.00460796533152461, 'High', 0.0, 0.0, 1.0, 0]
Bernie Sanders ['Human', 0.01731393299996853, 'High', 0.0, 0.0, 1.0, 0]
Bernie Sanders ['Human', 0.09087523818016052, 'Medium', 0.0, 0.0, 1.0, 0]
Gerald Malloy ['Human', 0.008890820667147636, 'High', 0.0, 0.0, 1.0, 0]
Gerald Malloy ['Human', 0.008487442508339882, 'High', 0.0, 0.0, 1.0, 0]
Dr Raul Garcia ['Human', 0.011922508555774888, 'High', 0.0, 0.0, 1.0, 0]
Maria Cantwell ['Human', 0.004642529413104057, 'High', 0.0, 0.0, 1.0, 0]
Maria Cantwell ['Human', 0.005232797112290023, 'High', 0.0, 0.0, 1.0, 0]
Maria Cantwell ['Human', 0.13206210732460022, 'Medium', 0.0, 0.0, 1.0, 0]
Eric Hovde ['Human', 0.0043180715292692184, 'High', 0.0, 0.0, 1.0, 0]
Tammy Baldwin ['Human', 0.005102196242660284, 'High', 0.0, 0.0, 1.0, 0]
Tammy Baldwin ['Human', 0.015259616076946259, 'High', 0.0, 0.0, 1.0, 0]
Tammy Baldwin ['Human', 0.004686219617724419, 'High', 0.0, 0.0, 1.0, 0]
Glenn Elliott ['Human', 0.10337324101816525, 'Medium', 0.0, 0.0, 1.0, 0]
Jim Justice ['Human', 0.004607409238815308, 'High', 0.0, 0.0, 1.0, 0]
Jim Justice ['Human', 0.004374942742288113, 'High', 0.0, 0.0, 1.0, 0]
John Barrasso ['Human', 0.005337647162377834, 'High', 0.0, 0.0, 1.0, 0]

In [154]:
#export done races:

#governor: DONE
#gov_added.to_csv("governor_text_detection.csv", index=False)

#attorney general: DONE
#ag_added.to_csv("ag_text_detection.csv", index=False)

#mayor: DONE
#mayor_added.to_csv("mayor_text_detection.csv", index=False)

#US Senate: DONE
#us_senate_added.to_csv("us_senate_detection.csv",index=False)

#US House

#State Senate

#State House

# Testing different sample lengths #

We originally sampled 40% of the visible text to run Pangram on it. Now, I will sample 60% and 80% of the original text and see if it makes a significant difference in the amount of text identified as AI.

In [31]:
combined_60 = pd.concat([gov_added, ag_added, mayor_added, us_senate_added], ignore_index=True)
combined_60

,content_id,candidate_id,candidate_name,page_url,page_type,link_type,unprocessed_text,cleaned_text,sampled_text,race_type,year,AI_label,assistance_score,confidence,fraction_ai,fraction_ai_assisted,fraction_human,num_ai_segments
0,1,6179,Andy Beshear,https://andybeshear.com/,home,campaign_site,Andy Beshear Menu Meet Andy Meet Jacqueline An...,Andy Beshear Menu Meet Andy Meet Jacqueline An...,Andy Beshear Menu Meet Andy Meet Jacqueline An...,Governor,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,6180,Daniel Cameron,https://cameronforkentucky.com/,home,campaign_site,Menu News Facebook Twitter Instagram Donate › ...,Menu News Facebook Twitter Instagram Donate S...,I'm In! QUICK DONATE $25 $50 $100 ENTER AMOUNT...,Governor,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,6180,Daniel Cameron,https://cameronforkentucky.com/policies/terms,policy,campaign_site,Menu News Facebook Twitter Instagram Donate › ...,Menu News Facebook Twitter Instagram Donate S...,Data Privacy We will not share or sell your pe...,Governor,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,6180,Daniel Cameron,https://cameronforkentucky.com/policies/privacy,policy,campaign_site,Menu News Facebook Twitter Instagram Donate › ...,Menu News Facebook Twitter Instagram Donate S...,"This Privacy Policy explains how we collect, u...",Governor,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,6180,Daniel Cameron,https://cameronforkentucky.com/issues/,policy,campaign_site,Menu News Facebook Twitter Instagram Donate › ...,Menu News Facebook Twitter Instagram Donate S...,He will always oppose the radical green agenda...,Governor,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,2828,6155,Tammy Baldwin,https://www.tammybaldwin.com/about/,about,campaign_site,About Tammy News Issues Get Involved Store Con...,About Tammy News Issues Get Involved Store Con...,"James Allen Veteran Vision Equity Act, passed ...",US Senate,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN
546,2829,6158,Glenn Elliott,https://www.elliottforwv.com,home,campaign_site,Elliott Wave Forecast Login Start 14-Day Trial...,Elliott Wave Forecast Login Start 14-Day Trial...,Retail Traders & Investors Join us never trade...,US Senate,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN
547,2830,6157,Jim Justice,http://jimjusticewv.com,home,campaign_site,Skip to content Endorsed by Trump Meet Jim Acc...,Skip to content Endorsed by Trump Meet Jim Acc...,Message frequency may vary. Reply stop to stop...,US Senate,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN
548,2831,6157,Jim Justice,https://jimjusticewv.com/issues/,policy,campaign_site,Skip to content Endorsed by Trump Meet Jim Acc...,Skip to content Endorsed by Trump Meet Jim Acc...,Reply stop to stop and help for help. Mobile o...,US Senate,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN
549,2832,6159,John Barrasso,https://barrassoforwyoming.com/,home,campaign_site,Skip to content Your Senator Get Involved Buy ...,Skip to content Your Senator Get Involved Buy ...,Message and data rates may apply. Message freq...,US Senate,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
#use the same sampling method but fraction is 0.6
def _sample_text(text: str, fraction: float = 0.8, max_attempts: int = 5) -> str:
    """Return a contiguous ~40% sentence chunk starting at a random position.

    Retries up to max_attempts times to avoid chunks containing ``"ERROR"``.

    Args:
        text: Input text to sample from.
        fraction: Fraction of sentences to include.
        max_attempts: Maximum retry attempts to avoid ERROR-containing chunks.

    Returns:
        Sampled text string.
    """
    if not isinstance(text, str) or text.startswith("ERROR:") or text == "":
        return text
    sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if s.strip()]
    if not sentences:
        return text
    k = max(1, int(len(sentences) * fraction))
    max_start = max(0, len(sentences) - k)
    sample = ""
    for _ in range(max_attempts):
        start = random.randint(0, max_start)
        sample = " ".join(sentences[start : start + k])
        if "ERROR" not in sample:
            return sample
    return sample

In [37]:
combined_60['sampled_text_60'] = np.nan

In [43]:
combined_60['sampled_text_60'] = combined_60['cleaned_text'].apply(_sample_text)

In [80]:
combined_60['sampled_text_60'].str.split().str.len().mean()

394.7490909090909

In [59]:
#check_entire_race(combined_60)

Andy Beshear ['Human', 0.005448558833450079, 'High', 0.0, 0.0, 1.0, 0]
Daniel Cameron ['Human', 0.006664706394076347, 'High', 0.0, 0.0, 1.0, 0]
Daniel Cameron ['AI', 0.8605841576390795, 'Medium', 1.0, 0.0, 0.0, 1]
Daniel Cameron ['AI', 0.989897112051646, 'High', 1.0, 0.0, 0.0, 2]
Daniel Cameron ['Human', 0.2740520238876343, 'Low', 0.0, 0.0, 1.0, 0]
Jeff Landry ['Human', 0.0055374037474393845, 'High', 0.0, 0.0, 1.0, 0]
Jeff Landry ['Human', 0.01942707778936793, 'High', 0.0, 0.0, 1.0, 0]
Brandon Presley ['Human', 0.005743841469908754, 'High', 0.0, 0.0, 1.0, 0]
Tate Reeves ['Human', 0.004855262581259012, 'High', 0.0, 0.0, 1.0, 0]
Tate Reeves ['Human', 0.0048487186431884766, 'High', 0.0, 0.0, 1.0, 0]
Matt Meyer ['Human', 0.012467694775555602, 'High', 0.0, 0.0, 1.0, 0]
Michael Ramone ['Human', 0.006591524463146925, 'High', 0.0, 0.0, 1.0, 0]
Michael Ramone ['Human', 0.007156895939260721, 'High', 0.0, 0.0, 1.0, 0]
Michael Ramone ['Human', 0.009534815326333046, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.0045262109488248825, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.004663982894271612, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.006206499878317118, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.02097532915927115, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.029142282903194427, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.009848859161138535, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.030463827832136303, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.004467265669006372, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.005123802570999793, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.00488511684656545, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.005217322806221626, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.0055016265478645444, 'High', 0.0, 0.0, 1.0, 0]
Crystal Quade ['Human', 0.006166607607156038, 'High', 0.0, 0.0, 1.0, 0]
Mike Kehoe ['Human', 0.005464618094265461, 'High', 0.0, 0.0, 1.0, 0]
Greg Gianforte ['Human', 0.04150858148932457, 'Medium', 0.0, 0.0, 1.0, 0]
Greg Gianforte ['Human', 0.004338366910815239, 'High', 0.0, 0.0, 1.0, 0]
Ryan Busse ['Human', 0.036431673796431384, 'High', 0.0, 0.0, 1.0, 0]
Kelly Ayotte ['Human', 0.005464315880089998, 'High', 0.0, 0.0, 1.0, 0]
Josh Stein ['Human', 0.02546207420527935, 'High', 0.0, 0.0, 1.0, 0]
Josh Stein ['Human', 0.004602512754943399, 'High', 0.0, 0.0, 1.0, 0]
Mark Robinson ['Human', 0.0065654306672513485, 'High', 0.0, 0.0, 1.0, 0]
Mark Robinson ['Human', 0.3814038038253784, 'Low', 0.0, 0.0, 1.0, 0]
Mark Robinson ['Human', 0.007229924667626619, 'High', 0.0, 0.0, 1.0, 0]
Kelly Armstrong ['Human', 0.004859877625112025, 'High', 0.0, 0.0, 1.0, 0]
Kelly Armstrong ['Human', 0.004760652271754765, 'High', 0.0, 0.0, 1.0, 0]
Kelly Armstrong ['Human', 0.0068930315064443725, 'High', 0.0, 0.0, 1.0, 0]
Merill Piepkorn ['Human', 0.006967174354940653, 'High', 0.0, 0.0, 1.0, 0]
Merill Piepkorn ['Human', 0.004203817807137966, 'High', 0.0, 0.0, 1.0, 0]
Merill Piepkorn ['Human', 0.005598660092800856, 'High', 0.0, 0.0, 1.0, 0]
Spencer Cox ['Human', 0.005690740887075663, 'High', 0.0, 0.0, 1.0, 0]
Spencer Cox ['Human', 0.009014918548720222, 'High', 0.0, 0.0, 1.0, 0]
Esther Charlestin ['AI', 0.6866525044140919, 'Medium', 1.0, 0.0, 0.0, 2]
Phil Scott ['Human', 0.17425425350666046, 'Low', 0.0, 0.0, 1.0, 0]
Bob Ferguson ['Human', 0.043633148074150085, 'Medium', 0.0, 0.0, 1.0, 0]
Bob Ferguson ['Human', 0.004636275091845738, 'High', 0.0, 0.0, 1.0, 0]
Bob Ferguson ['Human', 0.004345966503024101, 'High', 0.0, 0.0, 1.0, 0]
Dave Reichert ['Human', 0.049446746706962585, 'Medium', 0.0, 0.0, 1.0, 0]
Dave Reichert ['Human', 0.0043695630098227415, 'High', 0.0, 0.0, 1.0, 0]
Dave Reichert ['Human', 0.004355421134581169, 'High', 0.0, 0.0, 1.0, 0]
Dave Reichert ['Human', 0.004626299720257521, 'High', 0.0, 0.0, 1.0, 0]
Dave Reichert ['Human', 0.004660197999328375, 'High', 0.0, 0.0, 1.0, 0]
Patrick Morrisey ['Human', 0.015787998214364052, 'High', 0.0, 0.0, 1.0, 0]
Patrick Morrisey ['Human', 0.0057120223595472875, 'High', 0.0, 0.0, 1.0, 0]
Patrick Morrisey ['Human', 0.08148383701752339, 'Medium', 0.0, 0.0, 1.0, 0]
Steve Williams ['Human', 0.006134348455816507, 'High', 0.0, 0.0, 1.0, 0]
Jack Ciattarelli ['Human', 0.009975949302315712, 'High', 0.0, 0.0, 1.0, 0]
Jack Ciattarelli ['Human', 0.005169536452740431, 'High', 0.0, 0.0, 1.0, 0]
Mikie Sherrill ['Human', 0.004669079091399908, 'High', 0.0, 0.0, 1.0, 0]
Mikie Sherrill ['Human', 0.005269959336146712, 'High', 0.0, 0.0, 1.0, 0]
Mikie Sherrill ['Human', 0.03459332138299942, 'High', 0.0, 0.0, 1.0, 0]
Mikie Sherrill ['Human', 0.004584163427352905, 'High', 0.0, 0.0, 1.0, 0]
Abigail Spanberger ['Human', 0.00534049142152071, 'High', 0.0, 0.0, 1.0, 0]
Winsome Earle-Sears ['Human', 0.009103337302803993, 'High', 0.0, 0.0, 1.0, 0]
Pamela Stevenson ['Human', 0.005958059336990118, 'High', 0.0, 0.0, 1.0, 0]
Russell Coleman ['Human', 0.0045260959304869175, 'High', 0.0, 0.0, 1.0, 0]
Russell Coleman ['Human', 0.00559851573780179, 'High', 0.0, 0.0, 1.0, 0]
Russell Coleman ['Human', 0.005870155058801174, 'High', 0.0, 0.0, 1.0, 0]
Lindsey Cheek ['Human', 0.0046578355942897155, 'High', 0.0, 0.0, 1.0, 0]
Liz Murrill ['Human', 0.05961539223790169, 'Medium', 0.0, 0.0, 1.0, 0]
Greta Martin ['Human', 0.26760101318359375, 'Medium', 0.0, 0.0, 1.0, 0]
Lynn Fitch ['Human', 0.020288800820708275, 'High', 0.0, 0.0, 1.0, 0]
Lynn Fitch ['Human', 0.006973292678594589, 'High', 0.0, 0.0, 1.0, 0]
Lynn Fitch ['Human', 0.004262613598257303, 'High', 0.0, 0.0, 1.0, 0]
Destiny Wells ['Human', 0.03563547064550221, 'High', 0.0, 0.0, 1.0, 0]
Destiny Wells ['Human', 0.3955415063763258, 'Low', 0.0, 0.0, 1.0, 0]
Destiny Wells ['AI', 0.9839209318161011, 'High', 1.0, 0.0, 0.0, 1]
Todd Rokita ['Human', 0.0043582068756222725, 'High', 0.0, 0.0, 1.0, 0]
Todd Rokita ['Human', 0.004400302829693943, 'High', 0.0, 0.0, 1.0, 0]
Andrew Bailey ['Human', 0.02854742482304573, 'High', 0.0, 0.0, 1.0, 0]
Elad Gross ['Human', 0.005090892314910889, 'High', 0.0, 0.0, 1.0, 0]
Elad Gross ['Human', 0.03437501937150955, 'Medium', 0.0, 0.0, 1.0, 0]
Austin Knudsen ['Human', 0.004142514429986477, 'High', 0.0, 0.0, 1.0, 0]
Dan Bishop ['Human', 0.03330504894256592, 'High', 0.0, 0.0, 1.0, 0]
Dan Bishop ['Human', 0.005032709799706936, 'High', 0.0, 0.0, 1.0, 0]
Dan Bishop ['Human', 0.010663164779543877, 'High', 0.0, 0.0, 1.0, 0]
Jeff Jackson ['Human', 0.0071310363709926605, 'High', 0.0, 0.0, 1.0, 0]
Dan Rayfield ['Human', 0.005163321631367911, 'High', 0.0, 0.0, 1.0, 0]
Will Lathrop ['Human', 0.004474644549190998, 'High', 0.0, 0.0, 1.0, 0]
Dave Sunday ['Human', 0.005987005773931742, 'High', 0.0, 0.0, 1.0, 0]
Dave Sunday ['Human', 0.007521238557707805, 'High', 0.0, 0.0, 1.0, 0]
Eugene Depasquale ['Human', 0.004949135705828667, 'High', 0.0, 0.0, 1.0, 0]
Eugene Depasquale ['Human', 0.07242988976404854, 'Medium', 0.0, 0.0, 1.0, 0]
Derek Brown ['Human', 0.004436280112713575, 'High', 0.0, 0.0, 1.0, 0]
Derek Brown ['Human', 0.004696488380432129, 'High', 0.0, 0.0, 1.0, 0]
Rudy Bautista ['Human', 0.00464397668838501, 'High', 0.0, 0.0, 1.0, 0]
Charity Clark ['Human', 0.11895681572731776, 'Medium', 0.0, 0.0, 1.0, 0]
Ture Nelson ['Human', 0.005501347128301859, 'High', 0.0, 0.0, 1.0, 0]
Nick Brown ['Human', 0.005272452719509602, 'High', 0.0, 0.0, 1.0, 0]
Nick Brown ['Human', 0.007078364857695146, 'High', 0.0, 0.0, 1.0, 0]
Pete Serrano ['Human', 0.32260262966156006, 'Low', 0.0, 0.0, 1.0, 0]
Pete Serrano ['Human', 0.0063364082016050816, 'High', 0.0, 0.0, 1.0, 0]
Jb Mccuskey ['Human', 0.009811925701797009, 'High', 0.0, 0.0, 1.0, 0]
Jb Mccuskey ['Human', 0.0051966141909360886, 'High', 0.0, 0.0, 1.0, 0]
Jb Mccuskey ['Human', 0.004646016284823418, 'High', 0.0, 0.0, 1.0, 0]
Teresa Toriseva ['Human', 0.004995912313461304, 'High', 0.0, 0.0, 1.0, 0]
Jay Jones ['Human', 0.00488841999322176, 'High', 0.0, 0.0, 1.0, 0]
Barrett Gilbreath ['Human', 0.012744815088808537, 'High', 0.0, 0.0, 1.0, 0]
Steven L. Reed ['Human', 0.042226385325193405, 'High', 0.0, 0.0, 1.0, 0]
Janet Wittenbraker ['Human', 0.48280510740588306, 'Low', 0.0, 0.0, 1.0, 0]
Regina Romero ['Human', 0.005351237021386623, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.006088282447308302, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.006204437180185172, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.004495224915444851, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.004400691948831081, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.004580395761877298, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.005096107721328735, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.004471723588981799, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.005041888915002346, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.00607499061152339, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.004505553748458624, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.010163426399230957, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.004685362729315574, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.018321271985769272, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.007723033893853426, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.008872808894159756, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.004812114564700967, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.004881552013203861, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.004688280054939871, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.007723033893853426, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.004508078098297119, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.004533504135906696, 'High', 0.0, 0.0, 1.0, 0]
Mike Coffman ['Human', 0.004558019907277661, 'High', 0.0, 0.0, 1.0, 0]
Mike Coffman ['Human', 0.004509176593273878, 'High', 0.0, 0.0, 1.0, 0]
Wayne W. Williams  ['Human', 0.007327733498877258, 'High', 0.0, 0.0, 1.0, 0]
Wayne W. Williams  ['Human', 0.010229247871586583, 'High', 0.0, 0.0, 1.0, 0]
Yemi Mobolade ['Human', 0.005763943772763014, 'High', 0.0, 0.0, 1.0, 0]
Yemi Mobolade ['Human', 0.019909654057731756, 'High', 0.0, 0.0, 1.0, 0]
Belinda Noah ['Human', 0.005370997136246866, 'High', 0.0, 0.0, 1.0, 0]
Buddy Dyer ['Human', 0.00655511487275362, 'High', 0.0, 0.0, 1.0, 0]
Buddy Dyer ['Human', 0.004695301833756578, 'High', 0.0, 0.0, 1.0, 0]
Buddy Dyer ['Human', 0.004625242477965583, 'High', 0.0, 0.0, 1.0, 0]
Buddy Dyer ['Human', 0.007024739868938923, 'High', 0.0, 0.0, 1.0, 0]
Buddy Dyer ['Human', 0.007024739868938923, 'High', 0.0, 0.0, 1.0, 0]
Daniel Davis ['Human', 0.004255427047610283, 'High', 0.0, 0.0, 1.0, 0]
Donna Deegan ['Human', 0.011098385883357237, 'High', 0.0, 0.0, 1.0, 0]
Donna Deegan ['Human', 0.00482678360456967, 'High', 0.0, 0.0, 1.0, 0]
Donna Deegan ['Human', 0.004549801388444999, 'High', 0.0, 0.0, 1.0, 0]
Donna Deegan ['Human', 0.004947478858837519, 'High', 0.0, 0.0, 1.0, 0]
Donna Deegan ['Human', 0.0074939782885408085, 'High', 0.0, 0.0, 1.0, 0]
Steve Dixon ['Human', 0.00672571174800396, 'High', 0.0, 0.0, 1.0, 0]
Lauren Mclean ['Human', 0.004298546817153692, 'High', 0.0, 0.0, 1.0, 0]
Mike Masterson ['Human', 0.08694068223444952, 'Medium', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.015315729193389416, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.008936970261856914, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.0047825961373746395, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.0062980144284665585, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.005514209158718586, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.005798825528472662, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.004969924106262624, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.0046510230749845505, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.005636607296764851, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.0073565589264035225, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.005334892775863409, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.0055497633293271065, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.004871304612606764, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.005332333967089653, 'High', 0.0, 0.0, 1.0, 0]
Jim Langfelder ['Human', 0.013436156325042248, 'High', 0.0, 0.0, 1.0, 0]
Jim Langfelder ['Human', 0.00696969497948885, 'High', 0.0, 0.0, 1.0, 0]
Misty Buscher ['Human', 0.004900379106402397, 'High', 0.0, 0.0, 1.0, 0]
Misty Buscher ['Human', 0.005506468936800957, 'High', 0.0, 0.0, 1.0, 0]
Paul Vallas ['Human', 0.010328578716143965, 'High', 0.0, 0.0, 1.0, 0]
Joe Hogsett ['Human', 0.019764529815506842, 'High', 0.0, 0.0, 1.0, 0]
Thomas Didier ['Human', 0.005159569904208183, 'High', 0.0, 0.0, 1.0, 0]
Tom Henry ['Human', 0.019446713849902153, 'High', 0.0, 0.0, 1.0, 0]
Connie Boesen ['Human', 0.029763104394078255, 'High', 0.0, 0.0, 1.0, 0]
Connie Boesen ['Mixed', 0.39775835280088323, 'High', 0.37473684210526315, 0.0, 0.6252631578947369, 1]
Josh Mandelbaum ['Human', 0.00516378041356802, 'High', 0.0, 0.0, 1.0, 0]
Josh Mandelbaum ['Human', 0.004365313798189163, 'High', 0.0, 0.0, 1.0, 0]
Josh Mandelbaum ['Human', 0.0049759577959775925, 'High', 0.0, 0.0, 1.0, 0]
Lily Wu ['Human', 0.00806301217734794, 'High', 0.0, 0.0, 1.0, 0]
Quinton Lucas ['Human', 0.004670279566198587, 'High', 0.0, 0.0, 1.0, 0]
Leirion Gaylor Baird ['Human', 0.006815340369939804, 'High', 0.0, 0.0, 1.0, 0]
Leirion Gaylor Baird ['Human', 0.0304166691203136, 'High', 0.0, 0.0, 1.0, 0]
Leirion Gaylor Baird ['Human', 0.02120167575776577, 'High', 0.0, 0.0, 1.0, 0]
Byron Champlin ['Human', 0.03032921567015971, 'Medium', 0.0, 0.0, 1.0, 0]
Kate West ['Human', 0.02092878791292952, 'High', 0.0, 0.0, 1.0, 0]
Leonardo Williams ['Human', 0.13928313553333282, 'Medium', 0.0, 0.0, 1.0, 0]
Leonardo Williams ['Human', 0.007722284644842148, 'High', 0.0, 0.0, 1.0, 0]
Mike Woodard ['Human', 0.004599614068865776, 'High', 0.0, 0.0, 1.0, 0]
Mike Woodard ['Human', 0.008322354406118393, 'High', 0.0, 0.0, 1.0, 0]
Misun Kim ['Human', 0.09806524217128754, 'Medium', 0.0, 0.0, 1.0, 0]
Andrew Ginther ['Human', 0.005623677279800177, 'High', 0.0, 0.0, 1.0, 0]
Andrew Ginther ['Human', 0.005274654373646793, 'High', 0.0, 0.0, 1.0, 0]
Cherelle Parker ['Human', 0.0050627581703548245, 'High', 0.0, 0.0, 1.0, 0]
Cherelle Parker ['Human', 0.004728985484689474, 'High', 0.0, 0.0, 1.0, 0]
Cherelle Parker ['Human', 0.005029127351008356, 'High', 0.0, 0.0, 1.0, 0]
Cherelle Parker ['Human', 0.004728985484689474, 'High', 0.0, 0.0, 1.0, 0]
David Oh ['Human', 0.005798178259283304, 'High', 0.0, 0.0, 1.0, 0]
Alice Rolli ['Human', 0.004872969351708889, 'High', 0.0, 0.0, 1.0, 0]
Freddie O'Connell ['Human', 0.0057958196848630905, 'High', 0.0, 0.0, 1.0, 0]
Freddie O'Connell ['Human', 0.0051845963462255895, 'High', 0.0, 0.0, 1.0, 0]
Freddie O'Connell ['Human', 0.004912248812615871, 'High', 0.0, 0.0, 1.0, 0]
Paul Young ['Human', 0.00550805265083909, 'High', 0.0, 0.0, 1.0, 0]
Paul Young ['Human', 0.005239840131253004, 'High', 0.0, 0.0, 1.0, 0]
Paul Young ['Human', 0.08580154925584793, 'Medium', 0.0, 0.0, 1.0, 0]
Christopher Schuchardt ['Human', 0.006509185303002596, 'High', 0.0, 0.0, 1.0, 0]
Christopher Schuchardt ['Human', 0.11334724251072381, 'Medium', 0.0, 0.0, 1.0, 0]
Eric Johnson ['Human', 0.005410624668002129, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004437727853655815, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.005310655105859041, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.005328902509063482, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004790651146322489, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.00481244745121027, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004720515438488552, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004790651146322489, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.5106384874085741, 'Low', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004254192113876343, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.005761755630373955, 'High', 0.0, 0.0, 1.0, 0]
Kendal Richardson ['Human', 0.008564625996061498, 'High', 0.0, 0.0, 1.0, 0]
Mattie Parker ['Human', 0.004654893185943365, 'High', 0.0, 0.0, 1.0, 0]
Mattie Parker ['Human', 0.0046619216445833445, 'High', 0.0, 0.0, 1.0, 0]
Roel Garcia ['Human', 0.007177046500146389, 'High', 0.0, 0.0, 1.0, 0]
Ron Nirenberg ['Human', 0.14671963453292847, 'Low', 0.0, 0.0, 1.0, 0]
Scott Lemay ['Human', 0.007699613459408283, 'High', 0.0, 0.0, 1.0, 0]
Erin Mendenhall ['Human', 0.00666092149913311, 'High', 0.0, 0.0, 1.0, 0]
Ross Anderson ['Human', 0.004776555389749803, 'High', 0.0, 0.0, 1.0, 0]
Dan Jones ['Human', 0.006550567883498748, 'High', 0.0, 0.0, 1.0, 0]
David Ross ['Human', 0.4644091725349426, 'Low', 0.0, 0.0, 1.0, 0]
David Ross ['AI', 0.767977255086104, 'Low', 1.0, 0.0, 0.0, 1]
Dontae Payne ['Human', 0.008829255452534804, 'High', 0.0, 0.0, 1.0, 0]
Dontae Payne ['Human', 0.027484779566388277, 'High', 0.0, 0.0, 1.0, 0]
Nadine Woodward ['Human', 0.005675720516592264, 'High', 0.0, 0.0, 1.0, 0]
Satya Rhodes-Conway ['Human', 0.00974940239468243, 'High', 0.0, 0.0, 1.0, 0]
Satya Rhodes-Conway ['Human', 0.004475279872377331, 'High', 0.0, 0.0, 1.0, 0]
Satya Rhodes-Conway ['Human', 0.018298937007784843, 'High', 0.0, 0.0, 1.0, 0]
Satya Rhodes-Conway ['Human', 0.004709197208285332, 'High', 0.0, 0.0, 1.0, 0]
Satya Rhodes-Conway ['Human', 0.004658605437725782, 'High', 0.0, 0.0, 1.0, 0]
Angela Rodell ['Human', 0.005711411125957966, 'High', 0.0, 0.0, 1.0, 0]
Beth Weldon ['Human', 0.011958532116194773, 'High', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.12144465744495392, 'Medium', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.12151335179805756, 'Medium', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.0049833571538329124, 'High', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.12151335179805756, 'Medium', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.01267136912792921, 'High', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.01267136912792921, 'High', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.01267136912792921, 'High', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.01267136912792921, 'High', 0.0, 0.0, 1.0, 0]
Suzanne Lafrance ['Human', 0.01759306582324724, 'High', 0.0, 0.0, 1.0, 0]
Suzanne Lafrance ['AI', 0.9813577731450399, 'High', 1.0, 0.0, 0.0, 2]
David Ortega ['Human', 0.010421297512948513, 'High', 0.0, 0.0, 1.0, 0]
Kate Gallego ['Human', 0.004584474489092827, 'High', 0.0, 0.0, 1.0, 0]
Lisa Borowsky ['Human', 0.012388506904244423, 'High', 0.0, 0.0, 1.0, 0]
Mark Freeman ['Human', 0.25670948301752405, 'Low', 0.0, 0.0, 1.0, 0]
Mark Freeman ['Human', 0.24960151314735413, 'Low', 0.0, 0.0, 1.0, 0]
Mark Freeman ['Human', 0.40222678055676325, 'Low', 0.0, 0.0, 1.0, 0]
Mark Freeman ['Human', 0.4713625422655007, 'Low', 0.0, 0.0, 1.0, 0]
Matt Evans ['Human', 0.004685853607952595, 'High', 0.0, 0.0, 1.0, 0]
Scott Anderson ['Human', 0.15113326907157898, 'Low', 0.0, 0.0, 1.0, 0]
Christina Fugazi ['Human', 0.01067397790029645, 'High', 0.0, 0.0, 1.0, 0]
Daniel Lurie ['Human', 0.008445133749010432, 'High', 0.0, 0.0, 1.0, 0]
Gregory Tatum ['AI', 0.9774109721183777, 'High', 1.0, 0.0, 0.0, 1]
Jessica Qattawi ['AI', 0.7991758087891416, 'Medium', 1.0, 0.0, 0.0, 4]
Kevin Mccarty ['Human', 0.0054008024744689465, 'High', 0.0, 0.0, 1.0, 0]
Larry Agran ['Human', 0.005732169182414914, 'High', 0.0, 0.0, 1.0, 0]
Larry Turner ['Human', 0.0046420651488006115, 'High', 0.0, 0.0, 1.0, 0]
London Breed ['Human', 0.0048829661682248116, 'High', 0.0, 0.0, 1.0, 0]
London Breed ['Human', 0.004347495535652541, 'High', 0.0, 0.0, 1.0, 0]
London Breed ['Human', 0.005243352614343166, 'High', 0.0, 0.0, 1.0, 0]
Matt Mahan ['Human', 0.00541558776361247, 'High', 0.0, 0.0, 1.0, 0]
Matt Mahan ['Human', 0.0059019864278926195, 'High', 0.0, 0.0, 1.0, 0]
Raj Salwan ['Human', 0.04892703518271446, 'Medium', 0.0, 0.0, 1.0, 0]
Tammy Kim ['Human', 0.2166740614177534, 'Medium', 0.0, 0.0, 1.0, 0]

In [63]:
#combined_60.to_csv("combined_60.csv")

80% sampling:

In [68]:
combined_80 = pd.concat([gov_added, ag_added, mayor_added, us_senate_added], ignore_index=True)

In [76]:
combined_80['sampled_text_80'] = np.nan
combined_80['sampled_text_80'] = combined_80['cleaned_text'].apply(_sample_text)

In [78]:
combined_80['sampled_text_80'].str.split().str.len().mean()

527.2963636363636

In [86]:
check_entire_race(combined_80)

Andy Beshear ['Human', 0.006113550625741482, 'High', 0.0, 0.0, 1.0, 0]

/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_25992/2497770618.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Human' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result
/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_25992/2497770618.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'High' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result

Daniel Cameron ['Human', 0.007358470465987921, 'High', 0.0, 0.0, 1.0, 0]
Daniel Cameron ['AI', 0.9640528308717828, 'High', 1.0, 0.0, 0.0, 2]
Daniel Cameron ['AI', 0.9897981413773128, 'High', 1.0, 0.0, 0.0, 2]
Daniel Cameron ['Human', 0.3512515399532764, 'Low', 0.0, 0.0, 1.0, 0]
Jeff Landry ['Human', 0.006167260347865522, 'High', 0.0, 0.0, 1.0, 0]
Jeff Landry ['Human', 0.01602179515437815, 'High', 0.0, 0.0, 1.0, 0]
Brandon Presley ['Human', 0.00574190810719436, 'High', 0.0, 0.0, 1.0, 0]
Tate Reeves ['Human', 0.004526725970208645, 'High', 0.0, 0.0, 1.0, 0]
Tate Reeves ['Human', 0.005101080518215895, 'High', 0.0, 0.0, 1.0, 0]
Matt Meyer ['Human', 0.011196104794443171, 'High', 0.0, 0.0, 1.0, 0]
Michael Ramone ['Human', 0.010066330432891846, 'High', 0.0, 0.0, 1.0, 0]
Michael Ramone ['Human', 0.005054440501650485, 'High', 0.0, 0.0, 1.0, 0]
Michael Ramone ['Human', 0.0047388505190610886, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.004622395616024733, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.0053262244910001755, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.005339571740478277, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.043597776576759895, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.009634001180529594, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.011672685498043019, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.013884634220240904, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.005005527659005789, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.004869003410630449, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.004914863768743949, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.005031159839586085, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.008692955098653294, 'High', 0.0, 0.0, 1.0, 0]
Crystal Quade ['Human', 0.004761755466461182, 'High', 0.0, 0.0, 1.0, 0]
Mike Kehoe ['Human', 0.004918149672448635, 'High', 0.0, 0.0, 1.0, 0]
Greg Gianforte ['Human', 0.052565742284059525, 'Medium', 0.0, 0.0, 1.0, 0]
Greg Gianforte ['Human', 0.005758089998077291, 'High', 0.0, 0.0, 1.0, 0]
Ryan Busse ['Human', 0.021958877239160724, 'High', 0.0, 0.0, 1.0, 0]
Kelly Ayotte ['Human', 0.024064507335424423, 'High', 0.0, 0.0, 1.0, 0]
Josh Stein ['Human', 0.020511874929070473, 'High', 0.0, 0.0, 1.0, 0]
Josh Stein ['Human', 0.0049067073624529355, 'High', 0.0, 0.0, 1.0, 0]
Mark Robinson ['Human', 0.008285748772323132, 'High', 0.0, 0.0, 1.0, 0]
Mark Robinson ['Human', 0.3778356909751892, 'Low', 0.0, 0.0, 1.0, 0]
Mark Robinson ['Human', 0.007600840181112289, 'High', 0.0, 0.0, 1.0, 0]
Kelly Armstrong ['Human', 0.007262608001895704, 'High', 0.0, 0.0, 1.0, 0]
Kelly Armstrong ['Human', 0.004772514325767671, 'High', 0.0, 0.0, 1.0, 0]
Kelly Armstrong ['Human', 0.010027161888397805, 'High', 0.0, 0.0, 1.0, 0]
Merill Piepkorn ['Human', 0.00506593519821763, 'High', 0.0, 0.0, 1.0, 0]
Merill Piepkorn ['Human', 0.004496739923548048, 'High', 0.0, 0.0, 1.0, 0]
Merill Piepkorn ['Human', 0.012303671799600124, 'High', 0.0, 0.0, 1.0, 0]
Spencer Cox ['Human', 0.005875046830624342, 'High', 0.0, 0.0, 1.0, 0]
Spencer Cox ['Human', 0.020499317092393644, 'High', 0.0, 0.0, 1.0, 0]
Esther Charlestin ['AI', 0.5551978717212507, 'Low', 1.0, 0.0, 0.0, 2]
Phil Scott ['Human', 0.17425425350666046, 'Low', 0.0, 0.0, 1.0, 0]
Bob Ferguson ['Human', 0.01930972933769226, 'High', 0.0, 0.0, 1.0, 0]
Bob Ferguson ['Human', 0.004826976638576536, 'High', 0.0, 0.0, 1.0, 0]
Bob Ferguson ['Human', 0.004838058608584106, 'High', 0.0, 0.0, 1.0, 0]
Dave Reichert ['Human', 0.007683839648962021, 'High', 0.0, 0.0, 1.0, 0]
Dave Reichert ['Human', 0.004656210650379459, 'High', 0.0, 0.0, 1.0, 0]
Dave Reichert ['Human', 0.004656210650379459, 'High', 0.0, 0.0, 1.0, 0]
Dave Reichert ['Human', 0.0047418983129318805, 'High', 0.0, 0.0, 1.0, 0]
Dave Reichert ['Human', 0.0047418983129318805, 'High', 0.0, 0.0, 1.0, 0]
Patrick Morrisey ['Human', 0.040557682514190674, 'High', 0.0, 0.0, 1.0, 0]
Patrick Morrisey ['Human', 0.008223197490324316, 'High', 0.0, 0.0, 1.0, 0]
Patrick Morrisey ['Human', 0.07733595334658666, 'Medium', 0.0, 0.0, 1.0, 0]
Steve Williams ['Human', 0.00806100107729435, 'High', 0.0, 0.0, 1.0, 0]
Jack Ciattarelli ['Human', 0.006385535467416048, 'High', 0.0, 0.0, 1.0, 0]
Jack Ciattarelli ['Human', 0.0047689336352050304, 'High', 0.0, 0.0, 1.0, 0]
Mikie Sherrill ['Human', 0.0051713078282773495, 'High', 0.0, 0.0, 1.0, 0]
Mikie Sherrill ['Human', 0.005437244831525263, 'High', 0.0, 0.0, 1.0, 0]
Mikie Sherrill ['Human', 0.05102066695690155, 'Medium', 0.0, 0.0, 1.0, 0]
Mikie Sherrill ['Human', 0.004739942805220684, 'High', 0.0, 0.0, 1.0, 0]
Abigail Spanberger ['Human', 0.005224892403930426, 'High', 0.0, 0.0, 1.0, 0]
Winsome Earle-Sears ['Human', 0.009103337302803993, 'High', 0.0, 0.0, 1.0, 0]
Pamela Stevenson ['Human', 0.0053667391528901855, 'High', 0.0, 0.0, 1.0, 0]
Russell Coleman ['Human', 0.004760091193020344, 'High', 0.0, 0.0, 1.0, 0]
Russell Coleman ['Human', 0.0063159004274526975, 'High', 0.0, 0.0, 1.0, 0]
Russell Coleman ['Human', 0.0062425422139414065, 'High', 0.0, 0.0, 1.0, 0]
Lindsey Cheek ['Human', 0.011001925689691425, 'High', 0.0, 0.0, 1.0, 0]
Liz Murrill ['Human', 0.05826689675450325, 'Medium', 0.0, 0.0, 1.0, 0]
Greta Martin ['AI', 0.9840516199668248, 'High', 1.0, 0.0, 0.0, 2]
Lynn Fitch ['Human', 0.015119008719921112, 'High', 0.0, 0.0, 1.0, 0]
Lynn Fitch ['Human', 0.024685028893873095, 'High', 0.0, 0.0, 1.0, 0]
Lynn Fitch ['Human', 0.00781699176877737, 'High', 0.0, 0.0, 1.0, 0]
Destiny Wells ['Human', 0.06285163711756468, 'Medium', 0.0, 0.0, 1.0, 0]
Destiny Wells ['Human', 0.15120097994804382, 'Low', 0.0, 0.0, 1.0, 0]
Destiny Wells ['Human', 0.20928151905536652, 'Low', 0.0, 0.0, 1.0, 0]
Todd Rokita ['Human', 0.003840557299554348, 'High', 0.0, 0.0, 1.0, 0]
Todd Rokita ['unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run', 'unable to run']

/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_25992/2497770618.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unable to run' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result
/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_25992/2497770618.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unable to run' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result
/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_25992/2497770618.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unable to run' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result
/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_25992/2497770618.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unable to run' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result
/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_25992/2497770618.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unable to run' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result

Andrew Bailey ['Human', 0.02854742482304573, 'High', 0.0, 0.0, 1.0, 0]
Elad Gross ['Human', 0.004487310536205769, 'High', 0.0, 0.0, 1.0, 0]
Elad Gross ['Human', 0.01693745329976082, 'High', 0.0, 0.0, 1.0, 0]
Austin Knudsen ['Human', 0.0043084025382995605, 'High', 0.0, 0.0, 1.0, 0]
Dan Bishop ['Human', 0.017700625583529472, 'High', 0.0, 0.0, 1.0, 0]
Dan Bishop ['Human', 0.0063428329303860664, 'High', 0.0, 0.0, 1.0, 0]
Dan Bishop ['Human', 0.010111949406564236, 'High', 0.0, 0.0, 1.0, 0]
Jeff Jackson ['Human', 0.006451108958572149, 'High', 0.0, 0.0, 1.0, 0]
Dan Rayfield ['Human', 0.005438329428090978, 'High', 0.0, 0.0, 1.0, 0]
Will Lathrop ['Human', 0.005409943405538797, 'High', 0.0, 0.0, 1.0, 0]
Dave Sunday ['Human', 0.004397788550704718, 'High', 0.0, 0.0, 1.0, 0]
Dave Sunday ['Human', 0.007755926204923704, 'High', 0.0, 0.0, 1.0, 0]
Eugene Depasquale ['Human', 0.005412740632891655, 'High', 0.0, 0.0, 1.0, 0]
Eugene Depasquale ['Human', 0.03664596416314857, 'Medium', 0.0, 0.0, 1.0, 0]
Derek Brown ['Human', 0.005293433554470539, 'High', 0.0, 0.0, 1.0, 0]
Derek Brown ['Human', 0.004497826099395752, 'High', 0.0, 0.0, 1.0, 0]
Rudy Bautista ['Human', 0.00431046774610877, 'High', 0.0, 0.0, 1.0, 0]
Charity Clark ['Human', 0.12822738968367084, 'Medium', 0.0, 0.0, 1.0, 0]
Ture Nelson ['Human', 0.003885337384417653, 'High', 0.0, 0.0, 1.0, 0]
Nick Brown ['Human', 0.005231623537838459, 'High', 0.0, 0.0, 1.0, 0]
Nick Brown ['Human', 0.018528248460208212, 'High', 0.0, 0.0, 1.0, 0]
Pete Serrano ['Human', 0.25547993183135986, 'Low', 0.0, 0.0, 1.0, 0]
Pete Serrano ['Human', 0.12427385151386261, 'Medium', 0.0, 0.0, 1.0, 0]
Jb Mccuskey ['Human', 0.013020290061831474, 'High', 0.0, 0.0, 1.0, 0]
Jb Mccuskey ['Human', 0.005631227071686578, 'High', 0.0, 0.0, 1.0, 0]
Jb Mccuskey ['Human', 0.005865974351763725, 'High', 0.0, 0.0, 1.0, 0]
Teresa Toriseva ['Human', 0.0059339022263884544, 'High', 0.0, 0.0, 1.0, 0]
Jay Jones ['Human', 0.005975242238491774, 'High', 0.0, 0.0, 1.0, 0]
Barrett Gilbreath ['Human', 0.00679363941308111, 'High', 0.0, 0.0, 1.0, 0]
Steven L. Reed ['Human', 0.042226385325193405, 'High', 0.0, 0.0, 1.0, 0]
Janet Wittenbraker ['Mixed', 0.6431715832240759, 'Low', 0.4240986717267552, 0.0, 0.5759013282732448, 2]
Regina Romero ['Human', 0.007798618261170174, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.005957782517229631, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.004494664593625607, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.004536515444188434, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.005046224592661019, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.0046123597615708905, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.005531290080398321, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.004961391451716837, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.005100837908685207, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.027118876576423645, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.004279461478637088, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.01053487416356802, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.004764924301516565, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.0098718630948237, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.025745192542672157, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.00719628812600054, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.006834173241274883, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.004888219780927338, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.0045187417688319475, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.026650497689843178, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.004343986511230469, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.0038426818791776896, 'High', 0.0, 0.0, 1.0, 0]
Mike Coffman ['Human', 0.005457677389638797, 'High', 0.0, 0.0, 1.0, 0]
Mike Coffman ['Human', 0.0040715038776397705, 'High', 0.0, 0.0, 1.0, 0]
Wayne W. Williams  ['Human', 0.012176621563932191, 'High', 0.0, 0.0, 1.0, 0]
Wayne W. Williams  ['Human', 0.008397353205183623, 'High', 0.0, 0.0, 1.0, 0]
Yemi Mobolade ['Human', 0.006124377716332674, 'High', 0.0, 0.0, 1.0, 0]
Yemi Mobolade ['Human', 0.005291757163564292, 'High', 0.0, 0.0, 1.0, 0]
Belinda Noah ['Human', 0.005188312937735602, 'High', 0.0, 0.0, 1.0, 0]
Buddy Dyer ['Human', 0.02201341837644577, 'High', 0.0, 0.0, 1.0, 0]
Buddy Dyer ['Human', 0.006696507626548213, 'High', 0.0, 0.0, 1.0, 0]
Buddy Dyer ['Human', 0.004929621320491331, 'High', 0.0, 0.0, 1.0, 0]
Buddy Dyer ['Human', 0.005475061479955912, 'High', 0.0, 0.0, 1.0, 0]
Buddy Dyer ['Human', 0.004141075536608696, 'High', 0.0, 0.0, 1.0, 0]
Daniel Davis ['Human', 0.035166047105815744, 'High', 0.0, 0.0, 1.0, 0]
Donna Deegan ['Human', 0.010067783289758318, 'High', 0.0, 0.0, 1.0, 0]
Donna Deegan ['Human', 0.0069079979877067245, 'High', 0.0, 0.0, 1.0, 0]
Donna Deegan ['Human', 0.0069079979877067245, 'High', 0.0, 0.0, 1.0, 0]
Donna Deegan ['Human', 0.00529846056717885, 'High', 0.0, 0.0, 1.0, 0]
Donna Deegan ['Human', 0.0051249549224006916, 'High', 0.0, 0.0, 1.0, 0]
Steve Dixon ['Human', 0.004980100318789482, 'High', 0.0, 0.0, 1.0, 0]
Lauren Mclean ['Human', 0.004026975017040968, 'High', 0.0, 0.0, 1.0, 0]
Mike Masterson ['Human', 0.018933082710848086, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.02035401202738285, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.008936970261856914, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.004810363054275513, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.006585674826055765, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.005144711118191481, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.004875937011092901, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.004716404054003457, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.004652751609683037, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.0067575364373624325, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.011767622083425522, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.0059022908098995686, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.005130870267748833, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.004944784566760063, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.005322618409991264, 'High', 0.0, 0.0, 1.0, 0]
Jim Langfelder ['Human', 0.023139383643865585, 'High', 0.0, 0.0, 1.0, 0]
Jim Langfelder ['Human', 0.015035697310749028, 'High', 0.0, 0.0, 1.0, 0]
Misty Buscher ['Human', 0.004698216915130615, 'High', 0.0, 0.0, 1.0, 0]
Misty Buscher ['Human', 0.005756455007940531, 'High', 0.0, 0.0, 1.0, 0]
Paul Vallas ['Human', 0.0127008742122497, 'High', 0.0, 0.0, 1.0, 0]
Joe Hogsett ['Human', 0.0626094919185908, 'High', 0.0, 0.0, 1.0, 0]
Thomas Didier ['Human', 0.004347904406201381, 'High', 0.0, 0.0, 1.0, 0]
Tom Henry ['Human', 0.0036128165666013956, 'High', 0.0, 0.0, 1.0, 0]
Connie Boesen ['Human', 0.050407446920871735, 'High', 0.0, 0.0, 1.0, 0]
Connie Boesen ['Human', 0.019150600096812315, 'High', 0.0, 0.0, 1.0, 0]
Josh Mandelbaum ['Human', 0.004619594197720289, 'High', 0.0, 0.0, 1.0, 0]
Josh Mandelbaum ['Human', 0.0041838418343104426, 'High', 0.0, 0.0, 1.0, 0]
Josh Mandelbaum ['Human', 0.005072547122836113, 'High', 0.0, 0.0, 1.0, 0]
Lily Wu ['Human', 0.008139297236995784, 'High', 0.0, 0.0, 1.0, 0]
Quinton Lucas ['Human', 0.004670279566198587, 'High', 0.0, 0.0, 1.0, 0]
Leirion Gaylor Baird ['Human', 0.014347647316753864, 'High', 0.0, 0.0, 1.0, 0]
Leirion Gaylor Baird ['Human', 0.006577654815583418, 'High', 0.0, 0.0, 1.0, 0]
Leirion Gaylor Baird ['Human', 0.014347647316753864, 'High', 0.0, 0.0, 1.0, 0]
Byron Champlin ['Human', 0.03197010886243672, 'Medium', 0.0, 0.0, 1.0, 0]
Kate West ['Human', 0.17829079886040955, 'High', 0.0, 0.0, 1.0, 0]
Leonardo Williams ['Human', 0.09676771610975266, 'Medium', 0.0, 0.0, 1.0, 0]
Leonardo Williams ['Human', 0.013177165761590004, 'High', 0.0, 0.0, 1.0, 0]
Mike Woodard ['Human', 0.005675499731053909, 'High', 0.0, 0.0, 1.0, 0]
Mike Woodard ['Human', 0.005971214734017849, 'High', 0.0, 0.0, 1.0, 0]
Misun Kim ['Human', 0.28645914793014526, 'Low', 0.0, 0.0, 1.0, 0]
Andrew Ginther ['Human', 0.005439026281237602, 'High', 0.0, 0.0, 1.0, 0]
Andrew Ginther ['Human', 0.004957118358750624, 'High', 0.0, 0.0, 1.0, 0]
Cherelle Parker ['Human', 0.004956677552157392, 'High', 0.0, 0.0, 1.0, 0]
Cherelle Parker ['Human', 0.004720559399870653, 'High', 0.0, 0.0, 1.0, 0]
Cherelle Parker ['Human', 0.004738659406371573, 'High', 0.0, 0.0, 1.0, 0]
Cherelle Parker ['Human', 0.004738659406371573, 'High', 0.0, 0.0, 1.0, 0]
David Oh ['Human', 0.007391274441033602, 'High', 0.0, 0.0, 1.0, 0]
Alice Rolli ['Human', 0.006403331644833088, 'High', 0.0, 0.0, 1.0, 0]
Freddie O'Connell ['Human', 0.005479536019265652, 'High', 0.0, 0.0, 1.0, 0]
Freddie O'Connell ['Human', 0.005312504729485314, 'High', 0.0, 0.0, 1.0, 0]
Freddie O'Connell ['Human', 0.00508418362992046, 'High', 0.0, 0.0, 1.0, 0]
Paul Young ['Human', 0.006528790574520826, 'High', 0.0, 0.0, 1.0, 0]
Paul Young ['Human', 0.00407471414655447, 'High', 0.0, 0.0, 1.0, 0]
Paul Young ['Human', 0.06389811635017395, 'Medium', 0.0, 0.0, 1.0, 0]
Christopher Schuchardt ['Human', 0.009636875241994858, 'High', 0.0, 0.0, 1.0, 0]
Christopher Schuchardt ['Mixed', 0.3041553930060196, 'High', 0.20377121307353863, 0.0, 0.7962287869264614, 1]
Eric Johnson ['Human', 0.004348469898104668, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004411616828292608, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.0046170357215617385, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004940054379403591, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004940054379403591, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004951541777700186, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004878231789916754, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004940054379403591, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.5586616252315832, 'Low', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004261089488863945, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.005507256370037794, 'High', 0.0, 0.0, 1.0, 0]
Kendal Richardson ['Human', 0.01116481889039278, 'High', 0.0, 0.0, 1.0, 0]
Mattie Parker ['Human', 0.004651104100048542, 'High', 0.0, 0.0, 1.0, 0]
Mattie Parker ['Human', 0.004925249144434929, 'High', 0.0, 0.0, 1.0, 0]
Roel Garcia ['Human', 0.008102098479866982, 'High', 0.0, 0.0, 1.0, 0]
Ron Nirenberg ['Human', 0.13432207703590393, 'Medium', 0.0, 0.0, 1.0, 0]
Scott Lemay ['Human', 0.007614778820425272, 'High', 0.0, 0.0, 1.0, 0]
Erin Mendenhall ['Human', 0.009746973402798176, 'High', 0.0, 0.0, 1.0, 0]
Ross Anderson ['Human', 0.004528848813658794, 'High', 0.0, 0.0, 1.0, 0]
Dan Jones ['Human', 0.0074153540201394585, 'High', 0.0, 0.0, 1.0, 0]
David Ross ['Human', 0.2807643413543701, 'Low', 0.0, 0.0, 1.0, 0]
David Ross ['Human', 0.4520073178268614, 'Low', 0.0, 0.0, 1.0, 0]
Dontae Payne ['Human', 0.006321884870776716, 'High', 0.0, 0.0, 1.0, 0]
Dontae Payne ['Human', 0.023156215677757705, 'High', 0.0, 0.0, 1.0, 0]
Nadine Woodward ['Human', 0.006007172035960815, 'High', 0.0, 0.0, 1.0, 0]
Satya Rhodes-Conway ['Human', 0.012961219674316309, 'High', 0.0, 0.0, 1.0, 0]
Satya Rhodes-Conway ['Human', 0.004245029435641751, 'High', 0.0, 0.0, 1.0, 0]
Satya Rhodes-Conway ['Human', 0.004925881512463093, 'High', 0.0, 0.0, 1.0, 0]
Satya Rhodes-Conway ['Human', 0.004537420812994242, 'High', 0.0, 0.0, 1.0, 0]
Satya Rhodes-Conway ['Human', 0.014221783727407455, 'High', 0.0, 0.0, 1.0, 0]
Angela Rodell ['Human', 0.22786414623260498, 'Low', 0.0, 0.0, 1.0, 0]
Beth Weldon ['Human', 0.005601780954748392, 'High', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.16895132176578045, 'Medium', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.13317686319351196, 'Medium', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.13317686319351196, 'Medium', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.13317686319351196, 'Medium', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.00615991884842515, 'High', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.13317686319351196, 'Medium', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.13317686319351196, 'Medium', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.00615991884842515, 'High', 0.0, 0.0, 1.0, 0]
Suzanne Lafrance ['Human', 0.014848416532399227, 'High', 0.0, 0.0, 1.0, 0]
Suzanne Lafrance ['AI', 0.9898381912046009, 'High', 1.0, 0.0, 0.0, 2]
David Ortega ['Human', 0.030853155243676156, 'High', 0.0, 0.0, 1.0, 0]
Kate Gallego ['Human', 0.0049101500771939754, 'High', 0.0, 0.0, 1.0, 0]
Lisa Borowsky ['Human', 0.007721489200114526, 'High', 0.0, 0.0, 1.0, 0]
Mark Freeman ['Human', 0.22568430009425855, 'Medium', 0.0, 0.0, 1.0, 0]
Mark Freeman ['AI', 0.5778232732880011, 'Low', 1.0, 0.0, 0.0, 1]
Mark Freeman ['AI', 0.7412737092193293, 'Low', 1.0, 0.0, 0.0, 1]
Mark Freeman ['Human', 0.42011399387680237, 'Low', 0.0, 0.0, 1.0, 0]
Matt Evans ['Human', 0.004258615896105766, 'High', 0.0, 0.0, 1.0, 0]
Scott Anderson ['Human', 0.2149081975221634, 'Low', 0.0, 0.0, 1.0, 0]
Christina Fugazi ['Human', 0.04573143467132468, 'High', 0.0, 0.0, 1.0, 0]
Daniel Lurie ['Human', 0.010125121754588854, 'High', 0.0, 0.0, 1.0, 0]
Gregory Tatum ['AI', 0.9855186343193054, 'High', 1.0, 0.0, 0.0, 1]
Jessica Qattawi ['AI', 0.9376845820691961, 'High', 1.0, 0.0, 0.0, 4]
Kevin Mccarty ['Human', 0.010122529231011868, 'High', 0.0, 0.0, 1.0, 0]
Larry Agran ['Human', 0.006370264823507409, 'High', 0.0, 0.0, 1.0, 0]
Larry Turner ['Human', 0.005857630246152568, 'High', 0.0, 0.0, 1.0, 0]
London Breed ['Human', 0.005293216090649366, 'High', 0.0, 0.0, 1.0, 0]
London Breed ['Human', 0.004205585772263603, 'High', 0.0, 0.0, 1.0, 0]
London Breed ['Human', 0.005688820965588093, 'High', 0.0, 0.0, 1.0, 0]
Matt Mahan ['Human', 0.005621367955528613, 'High', 0.0, 0.0, 1.0, 0]
Matt Mahan ['Human', 0.0060385056035000394, 'High', 0.0, 0.0, 1.0, 0]
Raj Salwan ['Human', 0.016829199368388528, 'High', 0.0, 0.0, 1.0, 0]
Tammy Kim ['Human', 0.18349517004722668, 'Medium', 0.0, 0.0, 1.0, 0]
Tammy Kim ['Mixed', 0.5978668182667175, 'Low', 0.12373225152129817, 0.4315415821501014, 0.4447261663286004, 1]
Todd Gloria ['Human', 0.008150825276970863, 'High', 0.0, 0.0, 1.0, 0]
Todd Gloria ['Human', 0.00576528502307153, 'High', 0.0, 0.0, 1.0, 0]
Tyrone Wade ['Human', 0.005091667175292969, 'High', 0.0, 0.0, 1.0, 0]
Valeria Amezcua ['Human', 0.0053880072198808195, 'High', 0.0, 0.0, 1.0, 0]
Valeria Amezcua ['Human', 0.2529201675206423, 'Low', 0.0, 0.0, 1.0, 0]
Vinnie Bacon ['Human', 0.014363802390208647, 'High', 0.0, 0.0, 1.0, 0]
Vinnie Bacon ['Human', 0.006307581804123603, 'High', 0.0, 0.0, 1.0, 0]
Rick Blangiardi ['Human', 0.1980527639389038, 'Low', 0.0, 0.0, 1.0, 0]
Layne Wilkerson ['Human', 0.08215336501598358, 'Medium', 0.0, 0.0, 1.0, 0]
Emile Edwards ['Human', 0.03025420793823691, 'High', 0.0, 0.0, 1.0, 0]
Sharon Weston Broome ['Human', 0.005127565863725836, 'High', 0.0, 0.0, 1.0, 0]
Brandon Scott ['Human', 0.004698770586401224, 'High', 0.0, 0.0, 1.0, 0]
Shannon Wright ['Human', 0.0044702547006419905, 'High', 0.0, 0.0, 1.0, 0]
Lori Bagwell ['Human', 0.006160025484859943, 'High', 0.0, 0.0, 1.0, 0]
Lori Bagwell ['Human', 0.013562948100199333, 'High', 0.0, 0.0, 1.0, 0]
Shelley Berkley ['Human', 0.005067731719464064, 'High', 0.0, 0.0, 1.0, 0]
Shelley Berkley ['Human', 0.005215725861489773, 'High', 0.0, 0.0, 1.0, 0]
Shelley Berkley ['Human', 0.004695696756243706, 'High', 0.0, 0.0, 1.0, 0]
Victoria Seaman ['Human', 0.17915727198123932, 'Low', 0.0, 0.0, 1.0, 0]
Janet Cowell ['Human', 0.005371308876136835, 'High', 0.0, 0.0, 1.0, 0]
Janet Cowell ['Human', 0.022818204015493393, 'High', 0.0, 0.0, 1.0, 0]
Joanne Allen ['Human', 0.023216936159965208, 'High', 0.0, 0.0, 1.0, 0]
Paul Fitts ['AI', 0.629240870475769, 'Low', 1.0, 0.0, 0.0, 1]
Paul Fitts ['Human', 0.00539750167951627, 'High', 0.0, 0.0, 1.0, 0]
Karen Keith ['Human', 0.040900394320487976, 'Medium', 0.0, 0.0, 1.0, 0]
Monroe Nichols ['Human', 0.008513425476849079, 'High', 0.0, 0.0, 1.0, 0]
Monroe Nichols ['Human', 0.004318910599168804, 'High', 0.0, 0.0, 1.0, 0]
Monroe Nichols ['Human', 0.004318910599168804, 'High', 0.0, 0.0, 1.0, 0]
Monroe Nichols ['Human', 0.0054892485898632845, 'High', 0.0, 0.0, 1.0, 0]
Monroe Nichols ['Human', 0.005420272080560347, 'High', 0.0, 0.0, 1.0, 0]
Carmen Rubio ['Human', 0.038934506475925446, 'High', 0.0, 0.0, 1.0, 0]
Mark Mcbrayer ['Human', 0.004584093162970523, 'High', 0.0, 0.0, 1.0, 0]
Michael Hunter ['Human', 0.0049513536505401134, 'High', 0.0, 0.0, 1.0, 0]
Steve Massengale ['Human', 0.006627904716879129, 'High', 0.0, 0.0, 1.0, 0]
Danny Avula ['Human', 0.005389514885517577, 'High', 0.0, 0.0, 1.0, 0]
Danny Avula ['Human', 0.005354991538327311, 'High', 0.0, 0.0, 1.0, 0]
Don Carey Iii ['Mixed', 0.598651962374409, 'Medium', 0.3406405206370954, 0.0, 0.6593594793629046, 2]
Don Carey Iii ['Mixed', 0.6016687372929059, 'Medium', 0.3223406054456282, 0.0, 0.6776593945543717, 2]
Kenny Alexander ['Human', 0.3730682134628296, 'Low', 0.0, 0.0, 1.0, 0]
Kenny Alexander ['Human', 0.3621483807898061, 'Low', 0.0, 0.0, 1.0, 0]
Kenny Alexander ['Human', 0.004986405372619629, 'High', 0.0, 0.0, 1.0, 0]
Richard West ['Human', 0.004135115072131157, 'High', 0.0, 0.0, 1.0, 0]
Thomas Leeman Jr. ['Human', 0.18509529531002045, 'Low', 0.0, 0.0, 1.0, 0]
Cavalier Johnson ['Human', 0.007526934612542391, 'High', 0.0, 0.0, 1.0, 0]
Cavalier Johnson ['Human', 0.005823131185024977, 'High', 0.0, 0.0, 1.0, 0]
David King ['AI', 0.852132260799408, 'Medium', 1.0, 0.0, 0.0, 1]
Lashunda Scales ['Human', 0.055016689002513885, 'Medium', 0.0, 0.0, 1.0, 0]
Lashunda Scales ['Human', 0.005444735754281282, 'High', 0.0, 0.0, 1.0, 0]
Randall Woodfin ['Human', 0.005358046231170495, 'High', 0.0, 0.0, 1.0, 0]
Randall Woodfin ['Human', 0.00569685042379812, 'High', 0.0, 0.0, 1.0, 0]
Randall Woodfin ['Human', 0.00572225797266044, 'High', 0.0, 0.0, 1.0, 0]
Randall Woodfin ['AI', 0.4981009142962721, 'Medium', 0.9637386683338544, 0.0, 0.03626133166614567, 3]
Randall Woodfin ['AI', 0.7777595178915436, 'Medium', 1.0, 0.0, 0.0, 3]
Barbara Lee ['Human', 0.05603519827127457, 'Medium', 0.0, 0.0, 1.0, 0]
Barbara Lee ['Human', 0.0271892212331295, 'High', 0.0, 0.0, 1.0, 0]
Loren Taylor ['Human', 0.006832362252932328, 'High', 0.0, 0.0, 1.0, 0]
Bryan Calvo ['Human', 0.09062279015779495, 'Medium', 0.0, 0.0, 1.0, 0]
Bryan Calvo ['AI', 0.6836699072892467, 'Low', 1.0, 0.0, 0.0, 1]
Bryan Calvo ['Human', 0.004247355246075636, 'High', 0.0, 0.0, 1.0, 0]
Eileen Higgins ['Human', 0.12802626937627792, 'Medium', 0.0, 0.0, 1.0, 0]
Emilio Gonzalez ['Human', 0.1953505115075545, 'Medium', 0.0, 0.0, 1.0, 0]
Jesus Tundidor ['Human', 0.0062505339157290845, 'High', 0.0, 0.0, 1.0, 0]
Andre Dickens ['Human', 0.02872530184686184, 'High', 0.0, 0.0, 1.0, 0]
Andre Dickens ['Mixed', 0.5650319971655313, 'Low', 0.5661864025213867, 0.0, 0.43381359747861326, 1]
Henry Mcclure ['Human', 0.24143901467323303, 'Low', 0.0, 0.0, 1.0, 0]
Spencer Duncan ['AI', 0.8189392685890198, 'Medium', 1.0, 0.0, 0.0, 1]
Spencer Duncan ['Human', 0.008585454515653826, 'High', 0.0, 0.0, 1.0, 0]
Helena Moreno ['Human', 0.00418961513787508, 'High', 0.0, 0.0, 1.0, 0]
Helena Moreno ['Human', 0.004264882765710354, 'High', 0.0, 0.0, 1.0, 0]
Jared Littmann ['Human', 0.04484128579497337, 'Medium', 0.0, 0.0, 1.0, 0]
Jared Littmann ['Human', 0.0057330261915922165, 'High', 0.0, 0.0, 1.0, 0]
Jared Littmann ['Human', 0.004849604119145726, 'High', 0.0, 0.0, 1.0, 0]
Andy Schor ['Human', 0.0050412156746130095, 'High', 0.0, 0.0, 1.0, 0]
Kelsea Hector ['Human', 0.029361948370933533, 'High', 0.0, 0.0, 1.0, 0]
Mary Sheffield ['Human', 0.0049224887181827355, 'High', 0.0, 0.0, 1.0, 0]
Solomon Kinloch ['Human', 0.02545914612710476, 'High', 0.0, 0.0, 1.0, 0]
Jacob Frey ['Human', 0.034810684621334076, 'Medium', 0.0, 0.0, 1.0, 0]
Jacob Frey ['Human', 0.09128463309717595, 'High', 0.0, 0.0, 1.0, 0]
Jacob Frey ['Human', 0.004851090256124735, 'High', 0.0, 0.0, 1.0, 0]

In [90]:
combined_80.to_csv("combined_80.csv")

In [92]:
combined_80['cleaned_text'].str.split().str.len().mean()

697.9872727272727

In [98]:
#run it on the entire text
combined_100 = pd.concat([gov_added, ag_added, mayor_added, us_senate_added], ignore_index=True)

In [100]:
check_entire_race(combined_100)

Andy Beshear ['Human', 0.005622072145342827, 'High', 0.0, 0.0, 1.0, 0]

/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_25992/133460498.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Human' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result
/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_25992/133460498.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'High' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result

Daniel Cameron ['Human', 0.01741171291048106, 'High', 0.0, 0.0, 1.0, 0]
Daniel Cameron ['AI', 0.8537339926549197, 'Medium', 1.0, 0.0, 0.0, 2]
Daniel Cameron ['AI', 0.9857575063194548, 'High', 1.0, 0.0, 0.0, 2]
Daniel Cameron ['Human', 0.28203206396467884, 'Low', 0.0, 0.0, 1.0, 0]
Jeff Landry ['Human', 0.006908764435838048, 'High', 0.0, 0.0, 1.0, 0]
Jeff Landry ['Human', 0.009802112141476263, 'High', 0.0, 0.0, 1.0, 0]
Brandon Presley ['Human', 0.004862438204110644, 'High', 0.0, 0.0, 1.0, 0]
Tate Reeves ['Human', 0.005038095638155937, 'High', 0.0, 0.0, 1.0, 0]
Tate Reeves ['Human', 0.005264014471322298, 'High', 0.0, 0.0, 1.0, 0]
Matt Meyer ['Human', 0.008963912827727783, 'High', 0.0, 0.0, 1.0, 0]
Michael Ramone ['Human', 0.007256772369146347, 'High', 0.0, 0.0, 1.0, 0]
Michael Ramone ['Human', 0.006030693394455334, 'High', 0.0, 0.0, 1.0, 0]
Michael Ramone ['Human', 0.00632522787200287, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.005547715350985527, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.005228396039456129, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.005682408530265093, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.027146770259754722, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.004895555321127176, 'High', 0.0, 0.0, 1.0, 0]
Jennifer Mccormick ['Human', 0.00758978874873923, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.014104182868161135, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.004948320118226164, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.004948320118226164, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.004948320118226164, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.004948320118226164, 'High', 0.0, 0.0, 1.0, 0]
Mike Braun ['Human', 0.018831288374488126, 'High', 0.0, 0.0, 1.0, 0]
Crystal Quade ['Human', 0.004889097834865634, 'High', 0.0, 0.0, 1.0, 0]
Mike Kehoe ['Human', 0.004964598920196295, 'High', 0.0, 0.0, 1.0, 0]
Greg Gianforte ['Human', 0.02469060474762782, 'High', 0.0, 0.0, 1.0, 0]
Greg Gianforte ['Human', 0.0057939300847162185, 'High', 0.0, 0.0, 1.0, 0]
Ryan Busse ['Human', 0.02140445920157858, 'High', 0.0, 0.0, 1.0, 0]
Kelly Ayotte ['Human', 0.02000441402196884, 'High', 0.0, 0.0, 1.0, 0]
Josh Stein ['Human', 0.013651163317263126, 'High', 0.0, 0.0, 1.0, 0]
Josh Stein ['Human', 0.005429176111069937, 'High', 0.0, 0.0, 1.0, 0]
Mark Robinson ['Human', 0.0057941037230193615, 'High', 0.0, 0.0, 1.0, 0]
Mark Robinson ['Human', 0.1749308854341507, 'Medium', 0.0, 0.0, 1.0, 0]
Mark Robinson ['Human', 0.0054872422479093075, 'High', 0.0, 0.0, 1.0, 0]
Kelly Armstrong ['Human', 0.0057553627371888455, 'High', 0.0, 0.0, 1.0, 0]
Kelly Armstrong ['Human', 0.00506406727274042, 'High', 0.0, 0.0, 1.0, 0]
Kelly Armstrong ['Human', 0.0078160660601712, 'High', 0.0, 0.0, 1.0, 0]
Merill Piepkorn ['Human', 0.006382393185049295, 'High', 0.0, 0.0, 1.0, 0]
Merill Piepkorn ['Human', 0.004444916636982401, 'High', 0.0, 0.0, 1.0, 0]
Merill Piepkorn ['Human', 0.008228353224694729, 'High', 0.0, 0.0, 1.0, 0]
Spencer Cox ['Human', 0.0066812592558562756, 'High', 0.0, 0.0, 1.0, 0]
Spencer Cox ['Human', 0.022158037513724062, 'High', 0.0, 0.0, 1.0, 0]
Esther Charlestin ['AI', 0.6845498105175793, 'Medium', 1.0, 0.0, 0.0, 2]
Phil Scott ['Human', 0.17425425350666046, 'Low', 0.0, 0.0, 1.0, 0]
Bob Ferguson ['Human', 0.014245782978832722, 'High', 0.0, 0.0, 1.0, 0]
Bob Ferguson ['Human', 0.004511695186681065, 'High', 0.0, 0.0, 1.0, 0]
Bob Ferguson ['Human', 0.005106917252608886, 'High', 0.0, 0.0, 1.0, 0]
Dave Reichert ['Human', 0.009574886411428452, 'High', 0.0, 0.0, 1.0, 0]
Dave Reichert ['Human', 0.004632417357403456, 'High', 0.0, 0.0, 1.0, 0]
Dave Reichert ['Human', 0.004632417357403456, 'High', 0.0, 0.0, 1.0, 0]
Dave Reichert ['Human', 0.004450207261834293, 'High', 0.0, 0.0, 1.0, 0]
Dave Reichert ['Human', 0.004450207261834293, 'High', 0.0, 0.0, 1.0, 0]
Patrick Morrisey ['Human', 0.030382492941700746, 'High', 0.0, 0.0, 1.0, 0]
Patrick Morrisey ['Human', 0.006788956111132152, 'High', 0.0, 0.0, 1.0, 0]
Patrick Morrisey ['Human', 0.04754756979294058, 'Medium', 0.0, 0.0, 1.0, 0]
Steve Williams ['Human', 0.008183032274246216, 'High', 0.0, 0.0, 1.0, 0]
Jack Ciattarelli ['Human', 0.017449110746383667, 'High', 0.0, 0.0, 1.0, 0]
Jack Ciattarelli ['Human', 0.005192071199417114, 'High', 0.0, 0.0, 1.0, 0]
Mikie Sherrill ['Human', 0.004827563650906086, 'High', 0.0, 0.0, 1.0, 0]
Mikie Sherrill ['Human', 0.007024898397948588, 'High', 0.0, 0.0, 1.0, 0]
Mikie Sherrill ['Human', 0.009312382899224758, 'High', 0.0, 0.0, 1.0, 0]
Mikie Sherrill ['Human', 0.005025173580471539, 'High', 0.0, 0.0, 1.0, 0]
Abigail Spanberger ['Human', 0.006664549000561237, 'High', 0.0, 0.0, 1.0, 0]
Winsome Earle-Sears ['Human', 0.009103337302803993, 'High', 0.0, 0.0, 1.0, 0]
Pamela Stevenson ['Human', 0.014916197788393634, 'High', 0.0, 0.0, 1.0, 0]
Russell Coleman ['Human', 0.005229796748608351, 'High', 0.0, 0.0, 1.0, 0]
Russell Coleman ['Human', 0.007453350855741641, 'High', 0.0, 0.0, 1.0, 0]
Russell Coleman ['Human', 0.007453350855741641, 'High', 0.0, 0.0, 1.0, 0]
Lindsey Cheek ['Human', 0.011306019993649833, 'High', 0.0, 0.0, 1.0, 0]
Liz Murrill ['Human', 0.03778199478983879, 'Medium', 0.0, 0.0, 1.0, 0]
Greta Martin ['Mixed', 0.6654485498451523, 'High', 0.6553079947575361, 0.0, 0.34469200524246396, 1]
Lynn Fitch ['Human', 0.0177762471139431, 'High', 0.0, 0.0, 1.0, 0]
Lynn Fitch ['Human', 0.009800147815522823, 'High', 0.0, 0.0, 1.0, 0]
Lynn Fitch ['Human', 0.0061004888266325, 'High', 0.0, 0.0, 1.0, 0]
Destiny Wells ['Human', 0.04826102823239129, 'Medium', 0.0, 0.0, 1.0, 0]
Destiny Wells ['Human', 0.223261946361351, 'Low', 0.0, 0.0, 1.0, 0]
Destiny Wells ['Human', 0.1374622881412506, 'Medium', 0.0, 0.0, 1.0, 0]
Todd Rokita ['Human', 0.0042047458700835705, 'High', 0.0, 0.0, 1.0, 0]
Todd Rokita ['Human', 0.004598125003987526, 'High', 0.0, 0.0, 1.0, 0]
Andrew Bailey ['Human', 0.005555612966418266, 'High', 0.0, 0.0, 1.0, 0]
Elad Gross ['Human', 0.004034966230392456, 'High', 0.0, 0.0, 1.0, 0]
Elad Gross ['Human', 0.009039598517119884, 'High', 0.0, 0.0, 1.0, 0]
Austin Knudsen ['Human', 0.004667533561587334, 'High', 0.0, 0.0, 1.0, 0]
Dan Bishop ['Human', 0.013322677463293076, 'High', 0.0, 0.0, 1.0, 0]
Dan Bishop ['Human', 0.00835855957120657, 'High', 0.0, 0.0, 1.0, 0]
Dan Bishop ['Human', 0.00835855957120657, 'High', 0.0, 0.0, 1.0, 0]
Jeff Jackson ['Human', 0.006939218001207337, 'High', 0.0, 0.0, 1.0, 0]
Dan Rayfield ['Human', 0.005930655745863566, 'High', 0.0, 0.0, 1.0, 0]
Will Lathrop ['Human', 0.009099765156861395, 'High', 0.0, 0.0, 1.0, 0]
Dave Sunday ['Human', 0.004765229765325785, 'High', 0.0, 0.0, 1.0, 0]
Dave Sunday ['Human', 0.007464526337180547, 'High', 0.0, 0.0, 1.0, 0]
Eugene Depasquale ['Human', 0.0066449944861233234, 'High', 0.0, 0.0, 1.0, 0]
Eugene Depasquale ['Human', 0.020966316876576546, 'High', 0.0, 0.0, 1.0, 0]
Derek Brown ['Human', 0.005218446720391512, 'High', 0.0, 0.0, 1.0, 0]
Derek Brown ['Human', 0.005014623980969191, 'High', 0.0, 0.0, 1.0, 0]
Rudy Bautista ['Human', 0.004536445019766688, 'High', 0.0, 0.0, 1.0, 0]
Charity Clark ['Human', 0.10404897690658481, 'Medium', 0.0, 0.0, 1.0, 0]
Ture Nelson ['Human', 0.005338128190487623, 'High', 0.0, 0.0, 1.0, 0]
Nick Brown ['Human', 0.005457740487056035, 'High', 0.0, 0.0, 1.0, 0]
Nick Brown ['Human', 0.018493551126435033, 'High', 0.0, 0.0, 1.0, 0]
Pete Serrano ['Human', 0.25941604375839233, 'Low', 0.0, 0.0, 1.0, 0]
Pete Serrano ['Human', 0.07198350876569748, 'Medium', 0.0, 0.0, 1.0, 0]
Jb Mccuskey ['Human', 0.0062449281103909016, 'High', 0.0, 0.0, 1.0, 0]
Jb Mccuskey ['Human', 0.005465810609659356, 'High', 0.0, 0.0, 1.0, 0]
Jb Mccuskey ['Human', 0.004962038629067441, 'High', 0.0, 0.0, 1.0, 0]
Teresa Toriseva ['Human', 0.006135383155196905, 'High', 0.0, 0.0, 1.0, 0]
Jay Jones ['Human', 0.005408721510320902, 'High', 0.0, 0.0, 1.0, 0]
Barrett Gilbreath ['Human', 0.014955960912629962, 'High', 0.0, 0.0, 1.0, 0]
Steven L. Reed ['Human', 0.042226385325193405, 'High', 0.0, 0.0, 1.0, 0]
Janet Wittenbraker ['Mixed', 0.6193043040865512, 'Low', 0.2747143566815698, 0.0, 0.7252856433184302, 2]
Regina Romero ['Human', 0.00855835739500998, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.008502480004379458, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.005446406605400358, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.004769644344277266, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.006783461220847029, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.004657607669165979, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.005528544075787067, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.0049228737635920485, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.006047308910638094, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.009296605363488197, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.004479825362795964, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.008433657698333263, 'High', 0.0, 0.0, 1.0, 0]
Kelly Brough ['Human', 0.005201405994335396, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.012090170668670908, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.017366057261824608, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.006523880203635326, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.007226745544062545, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.006661626417495049, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.004717370962712954, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.01747669093310833, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.0044628925621509555, 'High', 0.0, 0.0, 1.0, 0]
Michael Johnston ['Human', 0.0044628925621509555, 'High', 0.0, 0.0, 1.0, 0]
Mike Coffman ['Human', 0.005182979726264926, 'High', 0.0, 0.0, 1.0, 0]
Mike Coffman ['Human', 0.004513745196163654, 'High', 0.0, 0.0, 1.0, 0]
Wayne W. Williams  ['Human', 0.010218647459948353, 'High', 0.0, 0.0, 1.0, 0]
Wayne W. Williams  ['Human', 0.007912499553101502, 'High', 0.0, 0.0, 1.0, 0]
Yemi Mobolade ['Human', 0.006401149261474723, 'High', 0.0, 0.0, 1.0, 0]
Yemi Mobolade ['Human', 0.013318098621165153, 'High', 0.0, 0.0, 1.0, 0]
Belinda Noah ['Human', 0.005676600383947971, 'High', 0.0, 0.0, 1.0, 0]
Buddy Dyer ['Human', 0.012528994081852336, 'High', 0.0, 0.0, 1.0, 0]
Buddy Dyer ['Human', 0.005146919279719614, 'High', 0.0, 0.0, 1.0, 0]
Buddy Dyer ['Human', 0.005146929528425624, 'High', 0.0, 0.0, 1.0, 0]
Buddy Dyer ['Human', 0.005420804597503905, 'High', 0.0, 0.0, 1.0, 0]
Buddy Dyer ['Human', 0.005420804597503905, 'High', 0.0, 0.0, 1.0, 0]
Daniel Davis ['Human', 0.029059586713888818, 'High', 0.0, 0.0, 1.0, 0]
Donna Deegan ['Human', 0.011001152275733788, 'High', 0.0, 0.0, 1.0, 0]
Donna Deegan ['Human', 0.0067247962122790675, 'High', 0.0, 0.0, 1.0, 0]
Donna Deegan ['Human', 0.0067247962122790675, 'High', 0.0, 0.0, 1.0, 0]
Donna Deegan ['Human', 0.0067247962122790675, 'High', 0.0, 0.0, 1.0, 0]
Donna Deegan ['Human', 0.0067247962122790675, 'High', 0.0, 0.0, 1.0, 0]
Steve Dixon ['Human', 0.004686223808676004, 'High', 0.0, 0.0, 1.0, 0]
Lauren Mclean ['Human', 0.004132087808102369, 'High', 0.0, 0.0, 1.0, 0]
Mike Masterson ['Human', 0.05108428886520186, 'Medium', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.01710832118988037, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.008936970261856914, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.005632575096872946, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.007145222722707937, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.005994861014187336, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.0049467675594819915, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.004676228317077316, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.00506585554103367, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.007519220467656851, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.010364431189373136, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.006609989330172539, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.005240950093138963, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.0065711313088993644, 'High', 0.0, 0.0, 1.0, 0]
Brandon Johnson ['Human', 0.005241782404482365, 'High', 0.0, 0.0, 1.0, 0]
Jim Langfelder ['Human', 0.023296954110264778, 'High', 0.0, 0.0, 1.0, 0]
Jim Langfelder ['Human', 0.007563275757193981, 'High', 0.0, 0.0, 1.0, 0]
Misty Buscher ['Human', 0.004303110763430595, 'High', 0.0, 0.0, 1.0, 0]
Misty Buscher ['Human', 0.0054353647865355015, 'High', 0.0, 0.0, 1.0, 0]
Paul Vallas ['Human', 0.015856326591470682, 'High', 0.0, 0.0, 1.0, 0]
Joe Hogsett ['Human', 0.01744694183562099, 'High', 0.0, 0.0, 1.0, 0]
Thomas Didier ['Human', 0.004299142402097849, 'High', 0.0, 0.0, 1.0, 0]
Tom Henry ['Human', 0.004699720069766045, 'High', 0.0, 0.0, 1.0, 0]
Connie Boesen ['Human', 0.004501028324011713, 'High', 0.0, 0.0, 1.0, 0]
Connie Boesen ['Human', 0.009045247297538559, 'High', 0.0, 0.0, 1.0, 0]
Josh Mandelbaum ['Human', 0.0047171201634531226, 'High', 0.0, 0.0, 1.0, 0]
Josh Mandelbaum ['Human', 0.004734410557873724, 'High', 0.0, 0.0, 1.0, 0]
Josh Mandelbaum ['Human', 0.005270605304223649, 'High', 0.0, 0.0, 1.0, 0]
Lily Wu ['Human', 0.009872289093402334, 'High', 0.0, 0.0, 1.0, 0]
Quinton Lucas ['Human', 0.004670279566198587, 'High', 0.0, 0.0, 1.0, 0]
Leirion Gaylor Baird ['Human', 0.007881957106292248, 'High', 0.0, 0.0, 1.0, 0]
Leirion Gaylor Baird ['Human', 0.01136493764816388, 'High', 0.0, 0.0, 1.0, 0]
Leirion Gaylor Baird ['Human', 0.007881957106292248, 'High', 0.0, 0.0, 1.0, 0]
Byron Champlin ['Human', 0.023419703955526384, 'High', 0.0, 0.0, 1.0, 0]
Kate West ['Human', 0.058474328924134684, 'Medium', 0.0, 0.0, 1.0, 0]
Leonardo Williams ['Human', 0.03444976845639758, 'Medium', 0.0, 0.0, 1.0, 0]
Leonardo Williams ['Human', 0.013358678668737411, 'High', 0.0, 0.0, 1.0, 0]
Mike Woodard ['Human', 0.06531409958169158, 'Medium', 0.0, 0.0, 1.0, 0]
Mike Woodard ['Human', 0.005334475543349981, 'High', 0.0, 0.0, 1.0, 0]
Misun Kim ['Human', 0.27253466844558716, 'Low', 0.0, 0.0, 1.0, 0]
Andrew Ginther ['Human', 0.006812749016985652, 'High', 0.0, 0.0, 1.0, 0]
Andrew Ginther ['Human', 0.004853571452864951, 'High', 0.0, 0.0, 1.0, 0]
Cherelle Parker ['Human', 0.005004452993201776, 'High', 0.0, 0.0, 1.0, 0]
Cherelle Parker ['Human', 0.005004452993201776, 'High', 0.0, 0.0, 1.0, 0]
Cherelle Parker ['Human', 0.005004452993201776, 'High', 0.0, 0.0, 1.0, 0]
Cherelle Parker ['Human', 0.005004452993201776, 'High', 0.0, 0.0, 1.0, 0]
David Oh ['Human', 0.0052333008497953415, 'High', 0.0, 0.0, 1.0, 0]
Alice Rolli ['Human', 0.007174041122198105, 'High', 0.0, 0.0, 1.0, 0]
Freddie O'Connell ['Human', 0.008307452557519787, 'High', 0.0, 0.0, 1.0, 0]
Freddie O'Connell ['Human', 0.005684807734473601, 'High', 0.0, 0.0, 1.0, 0]
Freddie O'Connell ['Human', 0.005901767445329948, 'High', 0.0, 0.0, 1.0, 0]
Paul Young ['Human', 0.009236088953912258, 'High', 0.0, 0.0, 1.0, 0]
Paul Young ['Human', 0.005810065194964409, 'High', 0.0, 0.0, 1.0, 0]
Paul Young ['Human', 0.05296944081783295, 'Medium', 0.0, 0.0, 1.0, 0]
Christopher Schuchardt ['Human', 0.008300486228948172, 'High', 0.0, 0.0, 1.0, 0]
Christopher Schuchardt ['Mixed', 0.3725853508581497, 'High', 0.30074257425742573, 0.0, 0.6992574257425743, 2]
Eric Johnson ['Human', 0.004464170895516872, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004541831556707621, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004989860896279829, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004989860896279829, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004989860896279829, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004989860896279829, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004989860896279829, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004989860896279829, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.46413206252823036, 'Low', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.008135966008477326, 'High', 0.0, 0.0, 1.0, 0]
John Whitmire ['Human', 0.004619210958480835, 'High', 0.0, 0.0, 1.0, 0]
Kendal Richardson ['Human', 0.009027953671412197, 'High', 0.0, 0.0, 1.0, 0]
Mattie Parker ['Human', 0.004736748198047281, 'High', 0.0, 0.0, 1.0, 0]
Mattie Parker ['Human', 0.004552647138056768, 'High', 0.0, 0.0, 1.0, 0]
Roel Garcia ['Human', 0.015194263076409698, 'High', 0.0, 0.0, 1.0, 0]
Ron Nirenberg ['Human', 0.13021990821203766, 'Medium', 0.0, 0.0, 1.0, 0]
Scott Lemay ['Human', 0.007148632314056158, 'High', 0.0, 0.0, 1.0, 0]
Erin Mendenhall ['Human', 0.005217577796429396, 'High', 0.0, 0.0, 1.0, 0]
Ross Anderson ['Human', 0.004560243061533999, 'High', 0.0, 0.0, 1.0, 0]
Dan Jones ['Human', 0.007930754814272363, 'High', 0.0, 0.0, 1.0, 0]
David Ross ['Human', 0.2915286719799042, 'Low', 0.0, 0.0, 1.0, 0]
David Ross ['Human', 0.5332343984769765, 'Low', 0.0, 0.0, 1.0, 0]
Dontae Payne ['Human', 0.008540696990773236, 'High', 0.0, 0.0, 1.0, 0]
Dontae Payne ['Human', 0.018392936052412143, 'High', 0.0, 0.0, 1.0, 0]
Nadine Woodward ['Human', 0.005096241141745072, 'High', 0.0, 0.0, 1.0, 0]
Satya Rhodes-Conway ['Human', 0.009253885252620133, 'High', 0.0, 0.0, 1.0, 0]
Satya Rhodes-Conway ['Human', 0.004257518734101026, 'High', 0.0, 0.0, 1.0, 0]
Satya Rhodes-Conway ['Human', 0.005275556351989508, 'High', 0.0, 0.0, 1.0, 0]
Satya Rhodes-Conway ['Human', 0.004579420499794651, 'High', 0.0, 0.0, 1.0, 0]
Satya Rhodes-Conway ['Human', 0.007491049618245317, 'High', 0.0, 0.0, 1.0, 0]
Angela Rodell ['Human', 0.06382045149803162, 'Medium', 0.0, 0.0, 1.0, 0]
Beth Weldon ['Human', 0.00964596770363786, 'High', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.1513350505847484, 'Medium', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.0061294096522033215, 'High', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.0061294096522033215, 'High', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.0061294096522033215, 'High', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.0061294096522033215, 'High', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.0061294096522033215, 'High', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.0061294096522033215, 'High', 0.0, 0.0, 1.0, 0]
David Bronson ['Human', 0.0061294096522033215, 'High', 0.0, 0.0, 1.0, 0]
Suzanne Lafrance ['Human', 0.020048609692629886, 'High', 0.0, 0.0, 1.0, 0]
Suzanne Lafrance ['AI', 0.9863450726014974, 'High', 1.0, 0.0, 0.0, 3]
David Ortega ['Human', 0.008408734555511424, 'High', 0.0, 0.0, 1.0, 0]
Kate Gallego ['Human', 0.004654786549508572, 'High', 0.0, 0.0, 1.0, 0]
Lisa Borowsky ['Human', 0.011783057013027638, 'High', 0.0, 0.0, 1.0, 0]
Mark Freeman ['Human', 0.24462112184401508, 'Low', 0.0, 0.0, 1.0, 0]
Mark Freeman ['Human', 0.358809923924294, 'Low', 0.0, 0.0, 1.0, 0]
Mark Freeman ['Human', 0.358809923924294, 'Low', 0.0, 0.0, 1.0, 0]
Mark Freeman ['Human', 0.3506298467555872, 'Low', 0.0, 0.0, 1.0, 0]
Matt Evans ['Human', 0.004622744861990213, 'High', 0.0, 0.0, 1.0, 0]
Scott Anderson ['Human', 0.13743285834789276, 'Medium', 0.0, 0.0, 1.0, 0]
Christina Fugazi ['Human', 0.15675076719554557, 'High', 0.0, 0.0, 1.0, 0]
Daniel Lurie ['Human', 0.02814117177863847, 'High', 0.0, 0.0, 1.0, 0]
Gregory Tatum ['AI', 0.9735026359558105, 'High', 1.0, 0.0, 0.0, 1]
Jessica Qattawi ['AI', 0.8459202993359001, 'Medium', 1.0, 0.0, 0.0, 6]
Kevin Mccarty ['Human', 0.008582720533013344, 'High', 0.0, 0.0, 1.0, 0]
Larry Agran ['Human', 0.006103170533078136, 'High', 0.0, 0.0, 1.0, 0]
Larry Turner ['Human', 0.014138541961512647, 'High', 0.0, 0.0, 1.0, 0]
London Breed ['Human', 0.004776884013510965, 'High', 0.0, 0.0, 1.0, 0]
London Breed ['Human', 0.004437781925653411, 'High', 0.0, 0.0, 1.0, 0]
London Breed ['Human', 0.0060221180818708885, 'High', 0.0, 0.0, 1.0, 0]
Matt Mahan ['Human', 0.004797845005264712, 'High', 0.0, 0.0, 1.0, 0]
Matt Mahan ['Human', 0.006241828663215401, 'High', 0.0, 0.0, 1.0, 0]
Raj Salwan ['Human', 0.06544391730508263, 'High', 0.0, 0.0, 1.0, 0]
Tammy Kim ['Human', 0.20272386165082076, 'Medium', 0.0, 0.0, 1.0, 0]

/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_25992/133460498.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unable to run' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result
/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_25992/133460498.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unable to run' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result
/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_25992/133460498.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unable to run' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result
/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_25992/133460498.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unable to run' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result
/var/folders/17/gz6b52jj5cvfsq17xw_vghsh0000gn/T/ipykernel_25992/133460498.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unable to run' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  race_df.loc[idx, ['AI_label', 'assistance_score', 'confidence', 'fraction_ai', 'fraction_ai_assisted', 'fraction_human', 'num_ai_segments']] = result

Bruce Harrell ['Human', 0.005818919142104713, 'High', 0.0, 0.0, 1.0, 0]
Katie Wilson ['Human', 0.02058959292480722, 'High', 0.0, 0.0, 1.0, 0]
Kari Lake ['Human', 0.018480936708372264, 'High', 0.0, 0.0, 1.0, 0]
Kari Lake ['Human', 0.0064066625200212, 'High', 0.0, 0.0, 1.0, 0]
Kari Lake ['Human', 0.01179938337632588, 'High', 0.0, 0.0, 1.0, 0]
Ruben Gallego ['Human', 0.005455920231755015, 'High', 0.0, 0.0, 1.0, 0]
Ruben Gallego ['Human', 0.012681391090154648, 'High', 0.0, 0.0, 1.0, 0]
Ruben Gallego ['Human', 0.004696518182754517, 'High', 0.0, 0.0, 1.0, 0]
Ruben Gallego ['Human', 0.015933264046907425, 'High', 0.0, 0.0, 1.0, 0]
Ruben Gallego ['Human', 0.004739276133477688, 'High', 0.0, 0.0, 1.0, 0]
Ruben Gallego ['Human', 0.005614593866214688, 'High', 0.0, 0.0, 1.0, 0]
Ruben Gallego ['Human', 0.007262190466281027, 'High', 0.0, 0.0, 1.0, 0]
Ruben Gallego ['Human', 0.005546203814446926, 'High', 0.0, 0.0, 1.0, 0]
Adam B. Schiff ['Human', 0.004961222720642885, 'High', 0.0, 0.0, 1.0, 0]
Adam B. Schiff ['Human', 0.007625682279467583, 'High', 0.0, 0.0, 1.0, 0]
Adam B. Schiff ['Human', 0.005020452005108102, 'High', 0.0, 0.0, 1.0, 0]
Steve Garvey ['Human', 0.0065215532667934895, 'High', 0.0, 0.0, 1.0, 0]
Christopher S. Murphy ['Human', 0.004692892942234482, 'High', 0.0, 0.0, 1.0, 0]
Christopher S. Murphy ['Human', 0.00479358424093913, 'High', 0.0, 0.0, 1.0, 0]
Matthew M. Corey ['Human', 0.005952613893896341, 'High', 0.0, 0.0, 1.0, 0]
Lisa Blunt Rochester ['Human', 0.02899143702261859, 'High', 0.0, 0.0, 1.0, 0]
Lisa Blunt Rochester ['Human', 0.005003729369491339, 'High', 0.0, 0.0, 1.0, 0]
Lisa Blunt Rochester ['Human', 0.005003729369491339, 'High', 0.0, 0.0, 1.0, 0]
Lisa Blunt Rochester ['Human', 0.013762583405442647, 'High', 0.0, 0.0, 1.0, 0]
Lisa Blunt Rochester ['Human', 0.013762583405442647, 'High', 0.0, 0.0, 1.0, 0]
Debbie Mucarsel-Powell ['Human', 0.005405785056895443, 'High', 0.0, 0.0, 1.0, 0]
Rick Scott ['Human', 0.05358307884836738, 'Medium', 0.0, 0.0, 1.0, 0]
Bob Mcdermott ['Human', 0.1719538857308186, 'Medium', 0.0, 0.0, 1.0, 0]
Mazie K. Hirono ['Human', 0.00545576304042091, 'High', 0.0, 0.0, 1.0, 0]
Mazie K. Hirono ['Human', 0.004860627322664692, 'High', 0.0, 0.0, 1.0, 0]
Mazie K. Hirono ['Human', 0.004434998615276223, 'High', 0.0, 0.0, 1.0, 0]
Mazie K. Hirono ['Human', 0.004434998615276223, 'High', 0.0, 0.0, 1.0, 0]
Jim Banks ['Human', 0.004901179578155279, 'High', 0.0, 0.0, 1.0, 0]
Jim Banks ['Human', 0.005810014910138694, 'High', 0.0, 0.0, 1.0, 0]
Valerie Mccray ['Human', 0.0048001670168729684, 'High', 0.0, 0.0, 1.0, 0]
Valerie Mccray ['Human', 0.004465996932410306, 'High', 0.0, 0.0, 1.0, 0]
Valerie Mccray ['Human', 0.09440857873654286, 'High', 0.0, 0.0, 1.0, 0]
Elizabeth Ann Warren ['Human', 0.008690434508025646, 'High', 0.0, 0.0, 1.0, 0]
Elizabeth Ann Warren ['Human', 0.006367280508395255, 'High', 0.0, 0.0, 1.0, 0]
John Deaton ['Human', 0.007546731698313547, 'High', 0.0, 0.0, 1.0, 0]
John Deaton ['Human', 0.1049899480763882, 'Medium', 0.0, 0.0, 1.0, 0]
Angela Alsobrooks ['Human', 0.004292474230169319, 'High', 0.0, 0.0, 1.0, 0]
Angela Alsobrooks ['Human', 0.005584240425378084, 'High', 0.0, 0.0, 1.0, 0]
Larry Hogan ['Mixed', 0.31282747369771186, 'Low', 0.3175089331291475, 0.0, 0.6824910668708525, 1]
Angus S. King Jr. ['Human', 0.13028311729431152, 'Medium', 0.0, 0.0, 1.0, 0]
Angus S. King Jr. ['Human', 0.005089253187179565, 'High', 0.0, 0.0, 1.0, 0]
Demi Kouzounas ['Human', 0.005192141022740139, 'High', 0.0, 0.0, 1.0, 0]
Demi Kouzounas ['Human', 0.00855881439721478, 'High', 0.0, 0.0, 1.0, 0]
Elissa Slotkin ['Human', 0.005950173484494111, 'High', 0.0, 0.0, 1.0, 0]
Elissa Slotkin ['Human', 0.005085253498803537, 'High', 0.0, 0.0, 1.0, 0]
Elissa Slotkin ['Human', 0.005085253498803537, 'High', 0.0, 0.0, 1.0, 0]
Elissa Slotkin ['Human', 0.005085253498803537, 'High', 0.0, 0.0, 1.0, 0]
Elissa Slotkin ['Human', 0.005085253498803537, 'High', 0.0, 0.0, 1.0, 0]
Elissa Slotkin ['Human', 0.005085253498803537, 'High', 0.0, 0.0, 1.0, 0]
Mike Rogers ['Human', 0.026021647135106227, 'High', 0.0, 0.0, 1.0, 0]
Amy Klobuchar ['Human', 0.0058662849478423595, 'High', 0.0, 0.0, 1.0, 0]
Royce White ['Human', 0.22308179239432016, 'Low', 0.0, 0.0, 1.0, 0]
Josh Hawley ['Human', 0.005513362931432547, 'High', 0.0, 0.0, 1.0, 0]
Lucas Kunce ['Human', 0.004544168710708618, 'High', 0.0, 0.0, 1.0, 0]
Roger F. Wicker ['Human', 0.0064086830243468285, 'High', 0.0, 0.0, 1.0, 0]
Ty Pinkins ['Human', 0.004414435010403395, 'High', 0.0, 0.0, 1.0, 0]
Ty Pinkins ['Human', 0.00508709903806448, 'High', 0.0, 0.0, 1.0, 0]
Jon Tester ['Human', 0.006251531083964639, 'High', 0.0, 0.0, 1.0, 0]
Jon Tester ['Human', 0.004992970399218447, 'High', 0.0, 0.0, 1.0, 0]
Jon Tester ['Human', 0.0062904899241402745, 'High', 0.0, 0.0, 1.0, 0]
Tim Sheehy ['Human', 0.018437090376392004, 'High', 0.0, 0.0, 1.0, 0]
Kevin Cramer ['Human', 0.006585819646716118, 'High', 0.0, 0.0, 1.0, 0]
Kevin Cramer ['Human', 0.005441457498818636, 'High', 0.0, 0.0, 1.0, 0]
Kevin Cramer ['Human', 0.37472343155670756, 'Low', 0.0, 0.0, 1.0, 0]
Dan Osborn ['Human', 0.00927459355443716, 'High', 0.0, 0.0, 1.0, 0]
Dan Osborn ['Human', 0.004770081225780782, 'High', 0.0, 0.0, 1.0, 0]
Deb Fischer ['Human', 0.008845384862204944, 'High', 0.0, 0.0, 1.0, 0]
Andy Kim ['Human', 0.010957424266962335, 'High', 0.0, 0.0, 1.0, 0]
Andy Kim ['Human', 0.004807906690984964, 'High', 0.0, 0.0, 1.0, 0]
Andy Kim ['Human', 0.004298626270610839, 'High', 0.0, 0.0, 1.0, 0]
Martin Heinrich ['Human', 0.1944544743746519, 'Low', 0.0, 0.0, 1.0, 0]
Martin Heinrich ['Mixed', 0.5413868004424646, 'Medium', 0.7573989162150896, 0.0, 0.24260108378491035, 2]
Martin Heinrich ['Human', 0.029107860281905217, 'High', 0.0, 0.0, 1.0, 0]
Jacky S. Rosen ['Human', 0.005645079538226128, 'High', 0.0, 0.0, 1.0, 0]
Jacky S. Rosen ['Human', 0.00489982850720278, 'High', 0.0, 0.0, 1.0, 0]
Sam Brown ['Human', 0.04049536022845518, 'High', 0.0, 0.0, 1.0, 0]
Kirsten E. Gillibrand ['Human', 0.07003575930892053, 'High', 0.0, 0.0, 1.0, 0]
Kirsten E. Gillibrand ['Human', 0.07152344100303998, 'High', 0.0, 0.0, 1.0, 0]
Bernie Moreno ['Human', 0.013749327510595322, 'High', 0.0, 0.0, 1.0, 0]
Bernie Moreno ['Human', 0.01316188783606603, 'High', 0.0, 0.0, 1.0, 0]
Sherrod Brown ['Human', 0.004895873093725337, 'High', 0.0, 0.0, 1.0, 0]
Dave Mccormick ['Human', 0.011212132286918522, 'High', 0.0, 0.0, 1.0, 0]
Dave Mccormick ['Human', 0.00669182043662, 'High', 0.0, 0.0, 1.0, 0]
Robert P Casey Jr ['Human', 0.004752654279582202, 'High', 0.0, 0.0, 1.0, 0]
Robert P Casey Jr ['Human', 0.004583858732590358, 'High', 0.0, 0.0, 1.0, 0]
Sheldon Whitehouse ['Human', 0.06877490878105164, 'Medium', 0.0, 0.0, 1.0, 0]
Sheldon Whitehouse ['Human', 0.011781041510403156, 'High', 0.0, 0.0, 1.0, 0]
Marsha Blackburn ['Human', 0.013621808552502274, 'High', 0.0, 0.0, 1.0, 0]
Marsha Blackburn ['Human', 0.005568798165768385, 'High', 0.0, 0.0, 1.0, 0]
Marsha Blackburn ['Human', 0.006408325406179452, 'High', 0.0, 0.0, 1.0, 0]
Marsha Blackburn ['Human', 0.013016580360602926, 'High', 0.0, 0.0, 1.0, 0]
Marsha Blackburn ['Human', 0.00822795283747837, 'High', 0.0, 0.0, 1.0, 0]
Marsha Blackburn ['Human', 0.00844484680177023, 'High', 0.0, 0.0, 1.0, 0]
Colin Allred ['Human', 0.016759566962718964, 'High', 0.0, 0.0, 1.0, 0]
Ted Cruz ['Human', 0.005208172144678731, 'High', 0.0, 0.0, 1.0, 0]
Caroline Gleich ['Human', 0.017488114535808563, 'High', 0.0, 0.0, 1.0, 0]
John Curtis ['Human', 0.01917689054140023, 'High', 0.0, 0.0, 1.0, 0]
John Curtis ['Human', 0.005262728314846754, 'High', 0.0, 0.0, 1.0, 0]
Hung Cao ['Human', 0.01098454144731578, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.006269267138226757, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.005840467754751444, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.005840467754751444, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.004988599829461977, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.005036341682584449, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.0050890801086400945, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.004752573571308996, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.005416231446314412, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.011736616379383839, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.005551317444769666, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.010395306298354019, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.004699518030975014, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.004783125501126051, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.012757870745931372, 'High', 0.0, 0.0, 1.0, 0]
Timothy M. Kaine ['Human', 0.012757870745931372, 'High', 0.0, 0.0, 1.0, 0]
Bernie Sanders ['Human', 0.008639915954798781, 'High', 0.0, 0.0, 1.0, 0]
Bernie Sanders ['Human', 0.02111586045939475, 'High', 0.0, 0.0, 1.0, 0]
Gerald Malloy ['Human', 0.006044128444045782, 'High', 0.0, 0.0, 1.0, 0]
Gerald Malloy ['Human', 0.006269101984798908, 'High', 0.0, 0.0, 1.0, 0]
Dr Raul Garcia ['Human', 0.05303732971949675, 'High', 0.0, 0.0, 1.0, 0]
Maria Cantwell ['Human', 0.0066759418696165085, 'High', 0.0, 0.0, 1.0, 0]
Maria Cantwell ['Human', 0.006836194630677869, 'High', 0.0, 0.0, 1.0, 0]
Maria Cantwell ['Human', 0.00675754901021719, 'High', 0.0, 0.0, 1.0, 0]
Eric Hovde ['Human', 0.004320110660046339, 'High', 0.0, 0.0, 1.0, 0]
Tammy Baldwin ['Human', 0.011628670977039271, 'High', 0.0, 0.0, 1.0, 0]
Tammy Baldwin ['Human', 0.005945908684784977, 'High', 0.0, 0.0, 1.0, 0]
Tammy Baldwin ['Human', 0.004712671140457976, 'High', 0.0, 0.0, 1.0, 0]
Glenn Elliott ['Human', 0.09930547347219985, 'High', 0.0, 0.0, 1.0, 0]
Jim Justice ['Human', 0.09722410616966963, 'Medium', 0.0, 0.0, 1.0, 0]
Jim Justice ['Human', 0.005768393166363239, 'High', 0.0, 0.0, 1.0, 0]
John Barrasso ['Human', 0.004187327785663964, 'High', 0.0, 0.0, 1.0, 0]

In [102]:
combined_100.to_csv("combined_100.csv")